// ====================================================================
// DADOS SINAPI CURADOS - ~100 Composições Residenciais
// ====================================================================
// Preços de referência por estado (CE, SP, RJ, MG, BA)
// Ref: SINAPI Jan/2025 (valores aproximados)

export interface SinapiCompositionData {
  code: string;
  description: string;
  unit: string;
  category: string;       // Código da etapa (01-18)
  subcategory: string;    // Nome da etapa
  items: SinapiItemData[];
  // Preço unitário base (SP) - será ajustado por estado
  baseCost: number;
}

export interface SinapiItemData {
  code: string;
  description: string;
  unit: string;
  type: 'MATERIAL' | 'LABOR' | 'EQUIPMENT';
  coefficient: number;
  unitPrice: number;
}

// Fatores de ajuste por estado (relativo a SP=1.0)
export const STATE_PRICE_FACTORS: Record<string, number> = {
  SP: 1.00,
  RJ: 1.05,
  MG: 0.92,
  BA: 0.88,
  CE: 0.85,
};

export const SUPPORTED_STATES = ['CE', 'SP', 'RJ', 'MG', 'BA'];

// ====================================================================
// COMPOSIÇÕES SINAPI
// ====================================================================
export const SINAPI_COMPOSITIONS: SinapiCompositionData[] = [
  // ══════════════════════════════════════════════════════════════
  // ETAPA 01 - SERVIÇOS PRELIMINARES
  // ══════════════════════════════════════════════════════════════
  {
    code: 'SINAPI-73847',
    description: 'Limpeza mecanizada de terreno com camada vegetal',
    unit: 'm²',
    category: '01',
    subcategory: 'Serviços Preliminares',
    baseCost: 3.82,
    items: [
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 0.05, unitPrice: 18.55 },
      { code: 'INS-00002', description: 'Trator de esteiras', unit: 'h', type: 'EQUIPMENT', coefficient: 0.008, unitPrice: 285.00 },
    ],
  },
  {
    code: 'SINAPI-74077',
    description: 'Placa de obra em chapa de aço galvanizado (2,0x1,125m)',
    unit: 'un',
    category: '01',
    subcategory: 'Serviços Preliminares',
    baseCost: 482.50,
    items: [
      { code: 'INS-00003', description: 'Chapa aço galvanizado', unit: 'un', type: 'MATERIAL', coefficient: 1.0, unitPrice: 350.00 },
      { code: 'INS-00004', description: 'Pintura e adesivagem', unit: 'un', type: 'MATERIAL', coefficient: 1.0, unitPrice: 80.00 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 2.0, unitPrice: 18.55 },
      { code: 'INS-00005', description: 'Pedreiro', unit: 'h', type: 'LABOR', coefficient: 1.0, unitPrice: 23.10 },
    ],
  },
  {
    code: 'SINAPI-73948',
    description: 'Tapume de madeira compensada, h=2,20m',
    unit: 'm',
    category: '01',
    subcategory: 'Serviços Preliminares',
    baseCost: 78.30,
    items: [
      { code: 'INS-00006', description: 'Madeira compensada 10mm', unit: 'm²', type: 'MATERIAL', coefficient: 2.2, unitPrice: 22.50 },
      { code: 'INS-00007', description: 'Pontalete madeira 7,5x7,5cm', unit: 'm', type: 'MATERIAL', coefficient: 3.0, unitPrice: 5.80 },
      { code: 'INS-00008', description: 'Prego 18x27', unit: 'kg', type: 'MATERIAL', coefficient: 0.15, unitPrice: 14.50 },
      { code: 'INS-00009', description: 'Carpinteiro', unit: 'h', type: 'LABOR', coefficient: 0.8, unitPrice: 23.80 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 0.8, unitPrice: 18.55 },
    ],
  },
  {
    code: 'SINAPI-84275',
    description: 'Locação de obra com tábua corrida',
    unit: 'm',
    category: '01',
    subcategory: 'Serviços Preliminares',
    baseCost: 18.74,
    items: [
      { code: 'INS-00010', description: 'Tábua madeira 2,5x30cm', unit: 'm', type: 'MATERIAL', coefficient: 0.5, unitPrice: 12.00 },
      { code: 'INS-00007', description: 'Pontalete madeira 7,5x7,5cm', unit: 'm', type: 'MATERIAL', coefficient: 0.5, unitPrice: 5.80 },
      { code: 'INS-00008', description: 'Prego 18x27', unit: 'kg', type: 'MATERIAL', coefficient: 0.05, unitPrice: 14.50 },
      { code: 'INS-00005', description: 'Pedreiro', unit: 'h', type: 'LABOR', coefficient: 0.2, unitPrice: 23.10 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 0.3, unitPrice: 18.55 },
    ],
  },
  {
    code: 'SINAPI-74209',
    description: 'Barracão de obra em madeira compensada, piso cimentado',
    unit: 'm²',
    category: '01',
    subcategory: 'Serviços Preliminares',
    baseCost: 295.00,
    items: [
      { code: 'INS-00006', description: 'Madeira compensada 10mm', unit: 'm²', type: 'MATERIAL', coefficient: 3.0, unitPrice: 22.50 },
      { code: 'INS-00007', description: 'Pontalete madeira 7,5x7,5cm', unit: 'm', type: 'MATERIAL', coefficient: 5.0, unitPrice: 5.80 },
      { code: 'INS-00011', description: 'Cimento CP-II', unit: 'kg', type: 'MATERIAL', coefficient: 15.0, unitPrice: 0.62 },
      { code: 'INS-00012', description: 'Areia média', unit: 'm³', type: 'MATERIAL', coefficient: 0.03, unitPrice: 95.00 },
      { code: 'INS-00009', description: 'Carpinteiro', unit: 'h', type: 'LABOR', coefficient: 3.0, unitPrice: 23.80 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 4.0, unitPrice: 18.55 },
    ],
  },
  {
    code: 'SINAPI-74131',
    description: 'Instalação provisória elétrica para canteiro de obra',
    unit: 'un',
    category: '01',
    subcategory: 'Serviços Preliminares',
    baseCost: 1250.00,
    items: [
      { code: 'INS-00013', description: 'Quadro elétrico provisório', unit: 'un', type: 'MATERIAL', coefficient: 1.0, unitPrice: 650.00 },
      { code: 'INS-00014', description: 'Cabo elétrico 10mm²', unit: 'm', type: 'MATERIAL', coefficient: 30.0, unitPrice: 8.50 },
      { code: 'INS-00015', description: 'Eletricista', unit: 'h', type: 'LABOR', coefficient: 12.0, unitPrice: 25.50 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 6.0, unitPrice: 18.55 },
    ],
  },

  // ══════════════════════════════════════════════════════════════
  // ETAPA 02 - INFRAESTRUTURA (FUNDAÇÕES)
  // ══════════════════════════════════════════════════════════════
  {
    code: 'SINAPI-102487',
    description: 'Concreto ciclópico FCK=15MPa, 30% pedra de mão em volume real, inclusive lançamento (AF_05/2021)',
    unit: 'm³',
    category: '02',
    subcategory: 'Infraestrutura',
    baseCost: 485.00,
    items: [
      { code: 'INS-00140', description: 'Concreto usinado FCK 15MPa', unit: 'm³', type: 'MATERIAL', coefficient: 0.73, unitPrice: 380.00 },
      { code: 'INS-00141', description: 'Pedra de mão (rachão)', unit: 'm³', type: 'MATERIAL', coefficient: 0.33, unitPrice: 85.00 },
      { code: 'INS-00005', description: 'Pedreiro', unit: 'h', type: 'LABOR', coefficient: 1.5, unitPrice: 23.10 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 3.0, unitPrice: 18.55 },
      { code: 'INS-00142', description: 'Vibrador de imersão', unit: 'h', type: 'EQUIPMENT', coefficient: 0.5, unitPrice: 15.00 },
    ],
  },
  {
    code: 'CF-02001',
    description: 'Alvenaria de embasamento com tijolo furado, argamassa 1:3 (cimento e areia)',
    unit: 'm²',
    category: '02',
    subcategory: 'Infraestrutura',
    baseCost: 72.50,
    items: [
      { code: 'INS-00143', description: 'Tijolo furado 9x19x19cm', unit: 'un', type: 'MATERIAL', coefficient: 25.0, unitPrice: 0.72 },
      { code: 'INS-00011', description: 'Cimento CP-II', unit: 'kg', type: 'MATERIAL', coefficient: 6.5, unitPrice: 0.62 },
      { code: 'INS-00012', description: 'Areia média', unit: 'm³', type: 'MATERIAL', coefficient: 0.018, unitPrice: 95.00 },
      { code: 'INS-00005', description: 'Pedreiro', unit: 'h', type: 'LABOR', coefficient: 1.2, unitPrice: 23.10 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 0.8, unitPrice: 18.55 },
    ],
  },
  {
    code: 'SINAPI-93204',
    description: 'Cinta de amarração de alvenaria moldada in loco em concreto, com formas de madeira',
    unit: 'm',
    category: '02',
    subcategory: 'Infraestrutura',
    baseCost: 58.50,
    items: [
      { code: 'INS-00016', description: 'Concreto usinado FCK 25MPa', unit: 'm³', type: 'MATERIAL', coefficient: 0.015, unitPrice: 450.00 },
      { code: 'INS-00017', description: 'Aço CA-50 10mm', unit: 'kg', type: 'MATERIAL', coefficient: 3.2, unitPrice: 6.20 },
      { code: 'INS-00018', description: 'Forma de madeira', unit: 'm²', type: 'MATERIAL', coefficient: 0.4, unitPrice: 32.00 },
      { code: 'INS-00019', description: 'Arame recozido', unit: 'kg', type: 'MATERIAL', coefficient: 0.3, unitPrice: 12.80 },
      { code: 'INS-00005', description: 'Pedreiro', unit: 'h', type: 'LABOR', coefficient: 0.5, unitPrice: 23.10 },
      { code: 'INS-00009', description: 'Carpinteiro', unit: 'h', type: 'LABOR', coefficient: 0.3, unitPrice: 23.80 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 0.6, unitPrice: 18.55 },
    ],
  },
  {
    code: 'CF-02002',
    description: 'Arranque de pilar em concreto armado FCK=25MPa, inclusive forma, armação e concretagem',
    unit: 'un',
    category: '02',
    subcategory: 'Infraestrutura',
    baseCost: 145.00,
    items: [
      { code: 'INS-00016', description: 'Concreto usinado FCK 25MPa', unit: 'm³', type: 'MATERIAL', coefficient: 0.025, unitPrice: 450.00 },
      { code: 'INS-00017', description: 'Aço CA-50 10mm', unit: 'kg', type: 'MATERIAL', coefficient: 8.0, unitPrice: 6.20 },
      { code: 'INS-00144', description: 'Aço CA-60 5mm (estribo)', unit: 'kg', type: 'MATERIAL', coefficient: 2.5, unitPrice: 7.10 },
      { code: 'INS-00018', description: 'Forma de madeira', unit: 'm²', type: 'MATERIAL', coefficient: 0.5, unitPrice: 32.00 },
      { code: 'INS-00019', description: 'Arame recozido', unit: 'kg', type: 'MATERIAL', coefficient: 0.4, unitPrice: 12.80 },
      { code: 'INS-00020', description: 'Armador', unit: 'h', type: 'LABOR', coefficient: 1.0, unitPrice: 23.50 },
      { code: 'INS-00009', description: 'Carpinteiro', unit: 'h', type: 'LABOR', coefficient: 0.5, unitPrice: 23.80 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 1.2, unitPrice: 18.55 },
    ],
  },
  {
    code: 'CF-02003',
    description: 'Alvenaria de pedra argamassada (fundação), argamassa traço 1:4 (cimento e areia)',
    unit: 'm³',
    category: '02',
    subcategory: 'Infraestrutura',
    baseCost: 385.00,
    items: [
      { code: 'INS-00141', description: 'Pedra de mão (rachão)', unit: 'm³', type: 'MATERIAL', coefficient: 1.1, unitPrice: 85.00 },
      { code: 'INS-00011', description: 'Cimento CP-II', unit: 'kg', type: 'MATERIAL', coefficient: 95.0, unitPrice: 0.62 },
      { code: 'INS-00012', description: 'Areia média', unit: 'm³', type: 'MATERIAL', coefficient: 0.42, unitPrice: 95.00 },
      { code: 'INS-00005', description: 'Pedreiro', unit: 'h', type: 'LABOR', coefficient: 3.5, unitPrice: 23.10 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 4.0, unitPrice: 18.55 },
    ],
  },
  {
    code: 'SINAPI-79479',
    description: 'Escavação manual de vala, solo de 1ª categoria, prof. até 1,5m',
    unit: 'm³',
    category: '02',
    subcategory: 'Infraestrutura',
    baseCost: 52.80,
    items: [
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 2.85, unitPrice: 18.55 },
    ],
  },
  {
    code: 'SINAPI-94965',
    description: 'Sapata de concreto armado FCK=25MPa, incluindo formas',
    unit: 'm³',
    category: '02',
    subcategory: 'Infraestrutura',
    baseCost: 1285.00,
    items: [
      { code: 'INS-00016', description: 'Concreto usinado FCK 25MPa', unit: 'm³', type: 'MATERIAL', coefficient: 1.05, unitPrice: 450.00 },
      { code: 'INS-00017', description: 'Aço CA-50 10mm', unit: 'kg', type: 'MATERIAL', coefficient: 85.0, unitPrice: 6.20 },
      { code: 'INS-00018', description: 'Forma de madeira', unit: 'm²', type: 'MATERIAL', coefficient: 6.0, unitPrice: 32.00 },
      { code: 'INS-00019', description: 'Arame recozido', unit: 'kg', type: 'MATERIAL', coefficient: 1.5, unitPrice: 12.80 },
      { code: 'INS-00020', description: 'Armador', unit: 'h', type: 'LABOR', coefficient: 6.0, unitPrice: 23.50 },
      { code: 'INS-00009', description: 'Carpinteiro', unit: 'h', type: 'LABOR', coefficient: 4.0, unitPrice: 23.80 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 8.0, unitPrice: 18.55 },
    ],
  },
  {
    code: 'SINAPI-94970',
    description: 'Viga baldrame de concreto armado FCK=25MPa',
    unit: 'm³',
    category: '02',
    subcategory: 'Infraestrutura',
    baseCost: 1380.00,
    items: [
      { code: 'INS-00016', description: 'Concreto usinado FCK 25MPa', unit: 'm³', type: 'MATERIAL', coefficient: 1.05, unitPrice: 450.00 },
      { code: 'INS-00017', description: 'Aço CA-50 10mm', unit: 'kg', type: 'MATERIAL', coefficient: 95.0, unitPrice: 6.20 },
      { code: 'INS-00018', description: 'Forma de madeira', unit: 'm²', type: 'MATERIAL', coefficient: 8.0, unitPrice: 32.00 },
      { code: 'INS-00019', description: 'Arame recozido', unit: 'kg', type: 'MATERIAL', coefficient: 2.0, unitPrice: 12.80 },
      { code: 'INS-00020', description: 'Armador', unit: 'h', type: 'LABOR', coefficient: 7.0, unitPrice: 23.50 },
      { code: 'INS-00009', description: 'Carpinteiro', unit: 'h', type: 'LABOR', coefficient: 5.0, unitPrice: 23.80 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 10.0, unitPrice: 18.55 },
    ],
  },
  {
    code: 'SINAPI-96545',
    description: 'Estaca broca de concreto, diâmetro 25cm, prof. até 3m',
    unit: 'm',
    category: '02',
    subcategory: 'Infraestrutura',
    baseCost: 68.50,
    items: [
      { code: 'INS-00016', description: 'Concreto usinado FCK 25MPa', unit: 'm³', type: 'MATERIAL', coefficient: 0.055, unitPrice: 450.00 },
      { code: 'INS-00017', description: 'Aço CA-50 10mm', unit: 'kg', type: 'MATERIAL', coefficient: 3.5, unitPrice: 6.20 },
      { code: 'INS-00005', description: 'Pedreiro', unit: 'h', type: 'LABOR', coefficient: 0.5, unitPrice: 23.10 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 1.5, unitPrice: 18.55 },
    ],
  },
  {
    code: 'SINAPI-79480',
    description: 'Reaterro compactado de vala com solo local',
    unit: 'm³',
    category: '02',
    subcategory: 'Infraestrutura',
    baseCost: 32.50,
    items: [
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 1.2, unitPrice: 18.55 },
      { code: 'INS-00021', description: 'Compactador de solo manual', unit: 'h', type: 'EQUIPMENT', coefficient: 0.3, unitPrice: 15.80 },
    ],
  },

  // ══════════════════════════════════════════════════════════════
  // ETAPA 03 - SUPRAESTRUTURA
  // ══════════════════════════════════════════════════════════════
  {
    code: 'SINAPI-92775',
    description: 'Pilar de concreto armado FCK=25MPa, seção retangular',
    unit: 'm³',
    category: '03',
    subcategory: 'Supraestrutura',
    baseCost: 1850.00,
    items: [
      { code: 'INS-00016', description: 'Concreto usinado FCK 25MPa', unit: 'm³', type: 'MATERIAL', coefficient: 1.05, unitPrice: 450.00 },
      { code: 'INS-00017', description: 'Aço CA-50 10mm', unit: 'kg', type: 'MATERIAL', coefficient: 120.0, unitPrice: 6.20 },
      { code: 'INS-00018', description: 'Forma de madeira', unit: 'm²', type: 'MATERIAL', coefficient: 12.0, unitPrice: 32.00 },
      { code: 'INS-00019', description: 'Arame recozido', unit: 'kg', type: 'MATERIAL', coefficient: 2.5, unitPrice: 12.80 },
      { code: 'INS-00020', description: 'Armador', unit: 'h', type: 'LABOR', coefficient: 8.0, unitPrice: 23.50 },
      { code: 'INS-00009', description: 'Carpinteiro', unit: 'h', type: 'LABOR', coefficient: 8.0, unitPrice: 23.80 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 12.0, unitPrice: 18.55 },
    ],
  },
  {
    code: 'SINAPI-92776',
    description: 'Viga de concreto armado FCK=25MPa, seção retangular',
    unit: 'm³',
    category: '03',
    subcategory: 'Supraestrutura',
    baseCost: 1720.00,
    items: [
      { code: 'INS-00016', description: 'Concreto usinado FCK 25MPa', unit: 'm³', type: 'MATERIAL', coefficient: 1.05, unitPrice: 450.00 },
      { code: 'INS-00017', description: 'Aço CA-50 10mm', unit: 'kg', type: 'MATERIAL', coefficient: 110.0, unitPrice: 6.20 },
      { code: 'INS-00018', description: 'Forma de madeira', unit: 'm²', type: 'MATERIAL', coefficient: 10.0, unitPrice: 32.00 },
      { code: 'INS-00019', description: 'Arame recozido', unit: 'kg', type: 'MATERIAL', coefficient: 2.0, unitPrice: 12.80 },
      { code: 'INS-00020', description: 'Armador', unit: 'h', type: 'LABOR', coefficient: 7.0, unitPrice: 23.50 },
      { code: 'INS-00009', description: 'Carpinteiro', unit: 'h', type: 'LABOR', coefficient: 7.0, unitPrice: 23.80 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 10.0, unitPrice: 18.55 },
    ],
  },
  {
    code: 'SINAPI-94964',
    description: 'Laje maciça de concreto armado FCK=25MPa, e=10cm',
    unit: 'm²',
    category: '03',
    subcategory: 'Supraestrutura',
    baseCost: 185.00,
    items: [
      { code: 'INS-00016', description: 'Concreto usinado FCK 25MPa', unit: 'm³', type: 'MATERIAL', coefficient: 0.105, unitPrice: 450.00 },
      { code: 'INS-00017', description: 'Aço CA-50 10mm', unit: 'kg', type: 'MATERIAL', coefficient: 9.5, unitPrice: 6.20 },
      { code: 'INS-00018', description: 'Forma de madeira', unit: 'm²', type: 'MATERIAL', coefficient: 1.1, unitPrice: 32.00 },
      { code: 'INS-00020', description: 'Armador', unit: 'h', type: 'LABOR', coefficient: 0.6, unitPrice: 23.50 },
      { code: 'INS-00009', description: 'Carpinteiro', unit: 'h', type: 'LABOR', coefficient: 0.8, unitPrice: 23.80 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 1.0, unitPrice: 18.55 },
    ],
  },
  {
    code: 'SINAPI-92778',
    description: 'Laje pré-moldada com tavela cerâmica, tijolo H8, concreto FCK=30MPa, e=12cm',
    unit: 'm²',
    category: '03',
    subcategory: 'Supraestrutura',
    baseCost: 115.00,
    items: [
      { code: 'INS-00022', description: 'Vigota pré-moldada', unit: 'm', type: 'MATERIAL', coefficient: 2.5, unitPrice: 8.50 },
      { code: 'INS-00023', description: 'Tavela cerâmica', unit: 'un', type: 'MATERIAL', coefficient: 8.0, unitPrice: 2.80 },
      { code: 'INS-00173', description: 'Tijolo cerâmico H8 (lajota)', unit: 'un', type: 'MATERIAL', coefficient: 5.0, unitPrice: 1.65 },
      { code: 'INS-00145', description: 'Concreto usinado FCK 30MPa', unit: 'm³', type: 'MATERIAL', coefficient: 0.04, unitPrice: 510.00 },
      { code: 'INS-00017', description: 'Aço CA-50 10mm', unit: 'kg', type: 'MATERIAL', coefficient: 2.8, unitPrice: 6.20 },
      { code: 'INS-00005', description: 'Pedreiro', unit: 'h', type: 'LABOR', coefficient: 0.55, unitPrice: 23.10 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 0.9, unitPrice: 18.55 },
    ],
  },
  {
    code: 'SINAPI-92780',
    description: 'Escada de concreto armado FCK=25MPa, incluindo forma',
    unit: 'm³',
    category: '03',
    subcategory: 'Supraestrutura',
    baseCost: 2250.00,
    items: [
      { code: 'INS-00016', description: 'Concreto usinado FCK 25MPa', unit: 'm³', type: 'MATERIAL', coefficient: 1.05, unitPrice: 450.00 },
      { code: 'INS-00017', description: 'Aço CA-50 10mm', unit: 'kg', type: 'MATERIAL', coefficient: 130.0, unitPrice: 6.20 },
      { code: 'INS-00018', description: 'Forma de madeira', unit: 'm²', type: 'MATERIAL', coefficient: 15.0, unitPrice: 32.00 },
      { code: 'INS-00020', description: 'Armador', unit: 'h', type: 'LABOR', coefficient: 10.0, unitPrice: 23.50 },
      { code: 'INS-00009', description: 'Carpinteiro', unit: 'h', type: 'LABOR', coefficient: 12.0, unitPrice: 23.80 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 14.0, unitPrice: 18.55 },
    ],
  },
  {
    code: 'SINAPI-92775-30',
    description: 'Pilar de concreto armado FCK=30MPa, seção retangular, inclusive formas',
    unit: 'm³',
    category: '03',
    subcategory: 'Supraestrutura',
    baseCost: 2050.00,
    items: [
      { code: 'INS-00145', description: 'Concreto usinado FCK 30MPa', unit: 'm³', type: 'MATERIAL', coefficient: 1.05, unitPrice: 510.00 },
      { code: 'INS-00017', description: 'Aço CA-50 10mm', unit: 'kg', type: 'MATERIAL', coefficient: 130.0, unitPrice: 6.20 },
      { code: 'INS-00018', description: 'Forma de madeira', unit: 'm²', type: 'MATERIAL', coefficient: 12.0, unitPrice: 32.00 },
      { code: 'INS-00019', description: 'Arame recozido', unit: 'kg', type: 'MATERIAL', coefficient: 2.5, unitPrice: 12.80 },
      { code: 'INS-00020', description: 'Armador', unit: 'h', type: 'LABOR', coefficient: 9.0, unitPrice: 23.50 },
      { code: 'INS-00009', description: 'Carpinteiro', unit: 'h', type: 'LABOR', coefficient: 8.0, unitPrice: 23.80 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 13.0, unitPrice: 18.55 },
    ],
  },
  {
    code: 'SINAPI-92776-30',
    description: 'Viga de concreto armado FCK=30MPa, seção retangular, inclusive formas',
    unit: 'm³',
    category: '03',
    subcategory: 'Supraestrutura',
    baseCost: 1920.00,
    items: [
      { code: 'INS-00145', description: 'Concreto usinado FCK 30MPa', unit: 'm³', type: 'MATERIAL', coefficient: 1.05, unitPrice: 510.00 },
      { code: 'INS-00017', description: 'Aço CA-50 10mm', unit: 'kg', type: 'MATERIAL', coefficient: 120.0, unitPrice: 6.20 },
      { code: 'INS-00018', description: 'Forma de madeira', unit: 'm²', type: 'MATERIAL', coefficient: 10.0, unitPrice: 32.00 },
      { code: 'INS-00019', description: 'Arame recozido', unit: 'kg', type: 'MATERIAL', coefficient: 2.0, unitPrice: 12.80 },
      { code: 'INS-00020', description: 'Armador', unit: 'h', type: 'LABOR', coefficient: 8.0, unitPrice: 23.50 },
      { code: 'INS-00009', description: 'Carpinteiro', unit: 'h', type: 'LABOR', coefficient: 7.0, unitPrice: 23.80 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 11.0, unitPrice: 18.55 },
    ],
  },
  {
    code: 'SINAPI-94964-30',
    description: 'Laje maciça de concreto armado FCK=30MPa, e=10cm, inclusive formas',
    unit: 'm²',
    category: '03',
    subcategory: 'Supraestrutura',
    baseCost: 198.00,
    items: [
      { code: 'INS-00145', description: 'Concreto usinado FCK 30MPa', unit: 'm³', type: 'MATERIAL', coefficient: 0.105, unitPrice: 510.00 },
      { code: 'INS-00017', description: 'Aço CA-50 10mm', unit: 'kg', type: 'MATERIAL', coefficient: 9.5, unitPrice: 6.20 },
      { code: 'INS-00018', description: 'Forma de madeira', unit: 'm²', type: 'MATERIAL', coefficient: 1.1, unitPrice: 32.00 },
      { code: 'INS-00020', description: 'Armador', unit: 'h', type: 'LABOR', coefficient: 0.6, unitPrice: 23.50 },
      { code: 'INS-00009', description: 'Carpinteiro', unit: 'h', type: 'LABOR', coefficient: 0.8, unitPrice: 23.80 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 1.0, unitPrice: 18.55 },
    ],
  },
  {
    code: 'CF-03001',
    description: 'Escada em estrutura metálica com degraus de madeira maciça, inclusive soldagem e acabamento',
    unit: 'm²',
    category: '03',
    subcategory: 'Supraestrutura',
    baseCost: 1850.00,
    items: [
      { code: 'INS-00146', description: 'Perfil metálico estrutural (viga U)', unit: 'kg', type: 'MATERIAL', coefficient: 45.0, unitPrice: 12.50 },
      { code: 'INS-00147', description: 'Chapa de aço para base dos degraus', unit: 'kg', type: 'MATERIAL', coefficient: 12.0, unitPrice: 11.80 },
      { code: 'INS-00148', description: 'Degrau de madeira maciça (cumaru/jatobá) e=3cm', unit: 'un', type: 'MATERIAL', coefficient: 3.5, unitPrice: 120.00 },
      { code: 'INS-00149', description: 'Eletrodo para solda', unit: 'kg', type: 'MATERIAL', coefficient: 2.5, unitPrice: 22.00 },
      { code: 'INS-00150', description: 'Primer anticorrosivo e pintura esmalte', unit: 'l', type: 'MATERIAL', coefficient: 1.5, unitPrice: 45.00 },
      { code: 'INS-00151', description: 'Parafusos e conectores', unit: 'un', type: 'MATERIAL', coefficient: 15.0, unitPrice: 2.80 },
      { code: 'INS-00152', description: 'Serralheiro/Soldador', unit: 'h', type: 'LABOR', coefficient: 6.0, unitPrice: 32.00 },
      { code: 'INS-00009', description: 'Carpinteiro', unit: 'h', type: 'LABOR', coefficient: 2.0, unitPrice: 23.80 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 3.0, unitPrice: 18.55 },
      { code: 'INS-00153', description: 'Máquina de solda', unit: 'h', type: 'EQUIPMENT', coefficient: 5.0, unitPrice: 18.00 },
    ],
  },
  {
    code: 'SINAPI-92781',
    description: 'Forma de madeira para estrutura de concreto',
    unit: 'm²',
    category: '03',
    subcategory: 'Supraestrutura',
    baseCost: 62.50,
    items: [
      { code: 'INS-00006', description: 'Madeira compensada 10mm', unit: 'm²', type: 'MATERIAL', coefficient: 1.1, unitPrice: 22.50 },
      { code: 'INS-00024', description: 'Sarrafo madeira', unit: 'm', type: 'MATERIAL', coefficient: 3.0, unitPrice: 3.80 },
      { code: 'INS-00008', description: 'Prego 18x27', unit: 'kg', type: 'MATERIAL', coefficient: 0.2, unitPrice: 14.50 },
      { code: 'INS-00025', description: 'Desmoldante', unit: 'l', type: 'MATERIAL', coefficient: 0.15, unitPrice: 12.50 },
      { code: 'INS-00009', description: 'Carpinteiro', unit: 'h', type: 'LABOR', coefficient: 0.8, unitPrice: 23.80 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 0.5, unitPrice: 18.55 },
    ],
  },

  // ══════════════════════════════════════════════════════════════
  // ETAPA 04 - ALVENARIA
  // ══════════════════════════════════════════════════════════════
  {
    code: 'SINAPI-87522',
    description: 'Alvenaria de bloco cerâmico 9x19x19cm, e=9cm, argamassa traço 1:2:8',
    unit: 'm²',
    category: '04',
    subcategory: 'Alvenaria',
    baseCost: 52.80,
    items: [
      { code: 'INS-00026', description: 'Bloco cerâmico 9x19x19cm', unit: 'un', type: 'MATERIAL', coefficient: 25.0, unitPrice: 0.68 },
      { code: 'INS-00011', description: 'Cimento CP-II', unit: 'kg', type: 'MATERIAL', coefficient: 3.78, unitPrice: 0.62 },
      { code: 'INS-00027', description: 'Cal hidratada', unit: 'kg', type: 'MATERIAL', coefficient: 2.52, unitPrice: 0.55 },
      { code: 'INS-00012', description: 'Areia média', unit: 'm³', type: 'MATERIAL', coefficient: 0.016, unitPrice: 95.00 },
      { code: 'INS-00005', description: 'Pedreiro', unit: 'h', type: 'LABOR', coefficient: 0.9, unitPrice: 23.10 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 0.6, unitPrice: 18.55 },
    ],
  },
  {
    code: 'SINAPI-87523',
    description: 'Alvenaria de bloco cerâmico 14x19x19cm, e=14cm, argamassa traço 1:2:8',
    unit: 'm²',
    category: '04',
    subcategory: 'Alvenaria',
    baseCost: 68.40,
    items: [
      { code: 'INS-00028', description: 'Bloco cerâmico 14x19x19cm', unit: 'un', type: 'MATERIAL', coefficient: 25.0, unitPrice: 0.98 },
      { code: 'INS-00011', description: 'Cimento CP-II', unit: 'kg', type: 'MATERIAL', coefficient: 5.04, unitPrice: 0.62 },
      { code: 'INS-00027', description: 'Cal hidratada', unit: 'kg', type: 'MATERIAL', coefficient: 3.36, unitPrice: 0.55 },
      { code: 'INS-00012', description: 'Areia média', unit: 'm³', type: 'MATERIAL', coefficient: 0.022, unitPrice: 95.00 },
      { code: 'INS-00005', description: 'Pedreiro', unit: 'h', type: 'LABOR', coefficient: 1.1, unitPrice: 23.10 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 0.7, unitPrice: 18.55 },
    ],
  },
  {
    code: 'SINAPI-87529',
    description: 'Verga de concreto armado para vãos de até 1,5m',
    unit: 'm',
    category: '04',
    subcategory: 'Alvenaria',
    baseCost: 42.50,
    items: [
      { code: 'INS-00016', description: 'Concreto usinado FCK 25MPa', unit: 'm³', type: 'MATERIAL', coefficient: 0.012, unitPrice: 450.00 },
      { code: 'INS-00017', description: 'Aço CA-50 10mm', unit: 'kg', type: 'MATERIAL', coefficient: 2.5, unitPrice: 6.20 },
      { code: 'INS-00018', description: 'Forma de madeira', unit: 'm²', type: 'MATERIAL', coefficient: 0.3, unitPrice: 32.00 },
      { code: 'INS-00005', description: 'Pedreiro', unit: 'h', type: 'LABOR', coefficient: 0.4, unitPrice: 23.10 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 0.5, unitPrice: 18.55 },
    ],
  },
  {
    code: 'SINAPI-87530',
    description: 'Contraverga de concreto armado para vãos de até 1,5m',
    unit: 'm',
    category: '04',
    subcategory: 'Alvenaria',
    baseCost: 38.20,
    items: [
      { code: 'INS-00016', description: 'Concreto usinado FCK 25MPa', unit: 'm³', type: 'MATERIAL', coefficient: 0.01, unitPrice: 450.00 },
      { code: 'INS-00017', description: 'Aço CA-50 10mm', unit: 'kg', type: 'MATERIAL', coefficient: 2.0, unitPrice: 6.20 },
      { code: 'INS-00018', description: 'Forma de madeira', unit: 'm²', type: 'MATERIAL', coefficient: 0.25, unitPrice: 32.00 },
      { code: 'INS-00005', description: 'Pedreiro', unit: 'h', type: 'LABOR', coefficient: 0.35, unitPrice: 23.10 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 0.45, unitPrice: 18.55 },
    ],
  },
  {
    code: 'CF-04001',
    description: 'Tela de amarração tipo Isofix/Soldafix em alvenaria com pistola finca pino (1 tela a cada 3 fiadas)',
    unit: 'm',
    category: '04',
    subcategory: 'Alvenaria',
    baseCost: 18.50,
    items: [
      { code: 'INS-00154', description: 'Tela de amarração galvanizada (Isofix/Soldafix) 7,5cm x 50cm', unit: 'un', type: 'MATERIAL', coefficient: 0.7, unitPrice: 4.80 },
      { code: 'INS-00155', description: 'Pino de aço para finca pino', unit: 'un', type: 'MATERIAL', coefficient: 1.4, unitPrice: 1.50 },
      { code: 'INS-00156', description: 'Cartucho para pistola finca pino', unit: 'un', type: 'MATERIAL', coefficient: 1.4, unitPrice: 2.20 },
      { code: 'INS-00005', description: 'Pedreiro', unit: 'h', type: 'LABOR', coefficient: 0.15, unitPrice: 23.10 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 0.1, unitPrice: 18.55 },
      { code: 'INS-00157', description: 'Pistola finca pino', unit: 'h', type: 'EQUIPMENT', coefficient: 0.1, unitPrice: 12.00 },
    ],
  },
  {
    code: 'SINAPI-87531',
    description: 'Encunhamento de alvenaria com argamassa expansiva',
    unit: 'm',
    category: '04',
    subcategory: 'Alvenaria',
    baseCost: 12.80,
    items: [
      { code: 'INS-00029', description: 'Argamassa expansiva', unit: 'kg', type: 'MATERIAL', coefficient: 0.8, unitPrice: 8.50 },
      { code: 'INS-00005', description: 'Pedreiro', unit: 'h', type: 'LABOR', coefficient: 0.2, unitPrice: 23.10 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 0.15, unitPrice: 18.55 },
    ],
  },

  // ══════════════════════════════════════════════════════════════
  // ETAPA 05 - COBERTURA
  // ══════════════════════════════════════════════════════════════
  {
    code: 'SINAPI-94227',
    description: 'Estrutura de madeira para telhado, vão até 8m, telha cerâmica',
    unit: 'm²',
    category: '05',
    subcategory: 'Cobertura',
    baseCost: 85.00,
    items: [
      { code: 'INS-00030', description: 'Caibro madeira 5x6cm', unit: 'm', type: 'MATERIAL', coefficient: 2.5, unitPrice: 6.80 },
      { code: 'INS-00031', description: 'Ripa madeira 1,5x5cm', unit: 'm', type: 'MATERIAL', coefficient: 3.5, unitPrice: 3.20 },
      { code: 'INS-00032', description: 'Terça madeira 6x12cm', unit: 'm', type: 'MATERIAL', coefficient: 0.8, unitPrice: 18.50 },
      { code: 'INS-00008', description: 'Prego 18x27', unit: 'kg', type: 'MATERIAL', coefficient: 0.15, unitPrice: 14.50 },
      { code: 'INS-00009', description: 'Carpinteiro', unit: 'h', type: 'LABOR', coefficient: 1.2, unitPrice: 23.80 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 0.8, unitPrice: 18.55 },
    ],
  },
  {
    code: 'SINAPI-94228',
    description: 'Telha cerâmica tipo colonial, incluso cumeeira',
    unit: 'm²',
    category: '05',
    subcategory: 'Cobertura',
    baseCost: 58.00,
    items: [
      { code: 'INS-00033', description: 'Telha cerâmica colonial', unit: 'un', type: 'MATERIAL', coefficient: 26.0, unitPrice: 1.50 },
      { code: 'INS-00034', description: 'Cumeeira cerâmica', unit: 'un', type: 'MATERIAL', coefficient: 1.5, unitPrice: 3.20 },
      { code: 'INS-00005', description: 'Pedreiro', unit: 'h', type: 'LABOR', coefficient: 0.6, unitPrice: 23.10 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 0.5, unitPrice: 18.55 },
    ],
  },
  {
    code: 'SINAPI-94230',
    description: 'Telha de fibrocimento ondulada 6mm',
    unit: 'm²',
    category: '05',
    subcategory: 'Cobertura',
    baseCost: 42.00,
    items: [
      { code: 'INS-00035', description: 'Telha fibrocimento 6mm', unit: 'm²', type: 'MATERIAL', coefficient: 1.1, unitPrice: 25.00 },
      { code: 'INS-00036', description: 'Parafuso fixação telha', unit: 'un', type: 'MATERIAL', coefficient: 4.0, unitPrice: 0.85 },
      { code: 'INS-00005', description: 'Pedreiro', unit: 'h', type: 'LABOR', coefficient: 0.3, unitPrice: 23.10 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 0.3, unitPrice: 18.55 },
    ],
  },
  {
    code: 'SINAPI-94232',
    description: 'Rufo de chapa galvanizada, desenvolvimento 33cm',
    unit: 'm',
    category: '05',
    subcategory: 'Cobertura',
    baseCost: 35.00,
    items: [
      { code: 'INS-00037', description: 'Chapa galvanizada #26', unit: 'm²', type: 'MATERIAL', coefficient: 0.35, unitPrice: 52.00 },
      { code: 'INS-00038', description: 'Funileiro', unit: 'h', type: 'LABOR', coefficient: 0.4, unitPrice: 25.00 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 0.2, unitPrice: 18.55 },
    ],
  },
  {
    code: 'SINAPI-94233',
    description: 'Calha de PVC semicircular, diâmetro 125mm',
    unit: 'm',
    category: '05',
    subcategory: 'Cobertura',
    baseCost: 28.50,
    items: [
      { code: 'INS-00039', description: 'Calha PVC 125mm', unit: 'm', type: 'MATERIAL', coefficient: 1.05, unitPrice: 15.80 },
      { code: 'INS-00040', description: 'Suporte calha PVC', unit: 'un', type: 'MATERIAL', coefficient: 2.0, unitPrice: 3.20 },
      { code: 'INS-00005', description: 'Pedreiro', unit: 'h', type: 'LABOR', coefficient: 0.25, unitPrice: 23.10 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 0.15, unitPrice: 18.55 },
    ],
  },

  {
    code: 'CF-05001',
    description: 'Laje impermeabilizada com manta asfáltica aluminizada, inclusive cimentado de regularização',
    unit: 'm²',
    category: '05',
    subcategory: 'Cobertura',
    baseCost: 128.00,
    items: [
      { code: 'INS-00158', description: 'Manta asfáltica aluminizada 3mm', unit: 'm²', type: 'MATERIAL', coefficient: 1.15, unitPrice: 42.00 },
      { code: 'INS-00042', description: 'Primer asfáltico', unit: 'l', type: 'MATERIAL', coefficient: 0.5, unitPrice: 18.00 },
      { code: 'INS-00011', description: 'Cimento CP-II', unit: 'kg', type: 'MATERIAL', coefficient: 10.0, unitPrice: 0.62 },
      { code: 'INS-00012', description: 'Areia média', unit: 'm³', type: 'MATERIAL', coefficient: 0.025, unitPrice: 95.00 },
      { code: 'INS-00043', description: 'Impermeabilizador', unit: 'h', type: 'LABOR', coefficient: 0.6, unitPrice: 28.00 },
      { code: 'INS-00005', description: 'Pedreiro', unit: 'h', type: 'LABOR', coefficient: 0.5, unitPrice: 23.10 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 0.6, unitPrice: 18.55 },
    ],
  },
  {
    code: 'CF-05002',
    description: 'Laje impermeabilizada com manta asfáltica 4mm, inclusive cimentado de regularização e proteção mecânica',
    unit: 'm²',
    category: '05',
    subcategory: 'Cobertura',
    baseCost: 165.00,
    items: [
      { code: 'INS-00159', description: 'Manta asfáltica 4mm', unit: 'm²', type: 'MATERIAL', coefficient: 1.15, unitPrice: 48.00 },
      { code: 'INS-00042', description: 'Primer asfáltico', unit: 'l', type: 'MATERIAL', coefficient: 0.5, unitPrice: 18.00 },
      { code: 'INS-00011', description: 'Cimento CP-II', unit: 'kg', type: 'MATERIAL', coefficient: 18.0, unitPrice: 0.62 },
      { code: 'INS-00012', description: 'Areia média', unit: 'm³', type: 'MATERIAL', coefficient: 0.045, unitPrice: 95.00 },
      { code: 'INS-00160', description: 'Argamassa para proteção mecânica e=3cm', unit: 'kg', type: 'MATERIAL', coefficient: 8.0, unitPrice: 0.55 },
      { code: 'INS-00043', description: 'Impermeabilizador', unit: 'h', type: 'LABOR', coefficient: 0.7, unitPrice: 28.00 },
      { code: 'INS-00005', description: 'Pedreiro', unit: 'h', type: 'LABOR', coefficient: 0.6, unitPrice: 23.10 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 0.8, unitPrice: 18.55 },
    ],
  },

  // ══════════════════════════════════════════════════════════════
  // ETAPA 06 - IMPERMEABILIZAÇÃO
  // ══════════════════════════════════════════════════════════════
  {
    code: 'SINAPI-98555',
    description: 'Impermeabilização com manta asfáltica 3mm, incluso primer',
    unit: 'm²',
    category: '06',
    subcategory: 'Impermeabilização',
    baseCost: 72.50,
    items: [
      { code: 'INS-00041', description: 'Manta asfáltica 3mm', unit: 'm²', type: 'MATERIAL', coefficient: 1.15, unitPrice: 32.00 },
      { code: 'INS-00042', description: 'Primer asfáltico', unit: 'l', type: 'MATERIAL', coefficient: 0.5, unitPrice: 18.00 },
      { code: 'INS-00043', description: 'Impermeabilizador', unit: 'h', type: 'LABOR', coefficient: 0.5, unitPrice: 28.00 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 0.4, unitPrice: 18.55 },
    ],
  },
  {
    code: 'SINAPI-98556',
    description: 'Impermeabilização de banheiro com argamassa polimérica',
    unit: 'm²',
    category: '06',
    subcategory: 'Impermeabilização',
    baseCost: 38.00,
    items: [
      { code: 'INS-00044', description: 'Argamassa polimérica', unit: 'kg', type: 'MATERIAL', coefficient: 3.0, unitPrice: 8.50 },
      { code: 'INS-00005', description: 'Pedreiro', unit: 'h', type: 'LABOR', coefficient: 0.4, unitPrice: 23.10 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 0.25, unitPrice: 18.55 },
    ],
  },
  {
    code: 'SINAPI-98557',
    description: 'Impermeabilização de fundação com emulsão asfáltica',
    unit: 'm²',
    category: '06',
    subcategory: 'Impermeabilização',
    baseCost: 18.50,
    items: [
      { code: 'INS-00045', description: 'Emulsão asfáltica', unit: 'l', type: 'MATERIAL', coefficient: 1.5, unitPrice: 8.00 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 0.3, unitPrice: 18.55 },
    ],
  },

  {
    code: 'CF-06001',
    description: 'Impermeabilização de paredes do piso térreo até 1m de altura com argamassa polimérica (3 demãos cruzadas)',
    unit: 'm²',
    category: '06',
    subcategory: 'Impermeabilização',
    baseCost: 48.00,
    items: [
      { code: 'INS-00044', description: 'Argamassa polimérica', unit: 'kg', type: 'MATERIAL', coefficient: 4.5, unitPrice: 8.50 },
      { code: 'INS-00161', description: 'Tela de poliéster para reforço', unit: 'm²', type: 'MATERIAL', coefficient: 1.1, unitPrice: 3.20 },
      { code: 'INS-00005', description: 'Pedreiro', unit: 'h', type: 'LABOR', coefficient: 0.5, unitPrice: 23.10 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 0.3, unitPrice: 18.55 },
    ],
  },
  {
    code: 'SINAPI-98555-4MM',
    description: 'Impermeabilização com manta asfáltica 4mm, incluso primer asfáltico',
    unit: 'm²',
    category: '06',
    subcategory: 'Impermeabilização',
    baseCost: 85.00,
    items: [
      { code: 'INS-00159', description: 'Manta asfáltica 4mm', unit: 'm²', type: 'MATERIAL', coefficient: 1.15, unitPrice: 48.00 },
      { code: 'INS-00042', description: 'Primer asfáltico', unit: 'l', type: 'MATERIAL', coefficient: 0.5, unitPrice: 18.00 },
      { code: 'INS-00043', description: 'Impermeabilizador', unit: 'h', type: 'LABOR', coefficient: 0.5, unitPrice: 28.00 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 0.4, unitPrice: 18.55 },
    ],
  },
  {
    code: 'CF-06002',
    description: 'Teste de estanqueidade em áreas impermeabilizadas (lâmina d\'água por 72h)',
    unit: 'm²',
    category: '06',
    subcategory: 'Impermeabilização',
    baseCost: 8.50,
    items: [
      { code: 'INS-00162', description: 'Água para teste', unit: 'm³', type: 'MATERIAL', coefficient: 0.05, unitPrice: 12.00 },
      { code: 'INS-00163', description: 'Fita adesiva para vedação provisória', unit: 'm', type: 'MATERIAL', coefficient: 0.5, unitPrice: 3.50 },
      { code: 'INS-00005', description: 'Pedreiro', unit: 'h', type: 'LABOR', coefficient: 0.15, unitPrice: 23.10 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 0.2, unitPrice: 18.55 },
    ],
  },

  {
    code: 'CF-06004',
    description: 'Argamassa de proteção mecânica sobre área impermeabilizada, traço 1:3, e=3cm, desempenada',
    unit: 'm²',
    category: '06',
    subcategory: 'Impermeabilização',
    baseCost: 35.00,
    items: [
      { code: 'INS-00011', description: 'Cimento CP-II', unit: 'kg', type: 'MATERIAL', coefficient: 11.0, unitPrice: 0.62 },
      { code: 'INS-00012', description: 'Areia média', unit: 'm³', type: 'MATERIAL', coefficient: 0.028, unitPrice: 95.00 },
      { code: 'INS-00175', description: 'Filme de polietileno (separação)', unit: 'm²', type: 'MATERIAL', coefficient: 1.1, unitPrice: 2.50 },
      { code: 'INS-00005', description: 'Pedreiro', unit: 'h', type: 'LABOR', coefficient: 0.5, unitPrice: 23.10 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 0.35, unitPrice: 18.55 },
    ],
  },
  {
    code: 'CF-06003',
    description: 'Argamassa de regularização com estudo de nível e caimentos para impermeabilização, traço 1:3, e=3cm',
    unit: 'm²',
    category: '06',
    subcategory: 'Impermeabilização',
    baseCost: 38.00,
    items: [
      { code: 'INS-00011', description: 'Cimento CP-II', unit: 'kg', type: 'MATERIAL', coefficient: 12.0, unitPrice: 0.62 },
      { code: 'INS-00012', description: 'Areia média', unit: 'm³', type: 'MATERIAL', coefficient: 0.03, unitPrice: 95.00 },
      { code: 'INS-00174', description: 'Aditivo impermeabilizante para argamassa', unit: 'l', type: 'MATERIAL', coefficient: 0.3, unitPrice: 18.00 },
      { code: 'INS-00005', description: 'Pedreiro', unit: 'h', type: 'LABOR', coefficient: 0.6, unitPrice: 23.10 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 0.4, unitPrice: 18.55 },
    ],
  },

  // ══════════════════════════════════════════════════════════════
  // ETAPA 07 - ESQUADRIAS
  // ══════════════════════════════════════════════════════════════
  {
    code: 'SINAPI-91338',
    description: 'Porta de madeira interna semi-oca 80x210cm, incluso marco e dobradiças',
    unit: 'un',
    category: '07',
    subcategory: 'Esquadrias',
    baseCost: 520.00,
    items: [
      { code: 'INS-00046', description: 'Porta semi-oca 80x210cm', unit: 'un', type: 'MATERIAL', coefficient: 1.0, unitPrice: 185.00 },
      { code: 'INS-00047', description: 'Marco/batente madeira', unit: 'un', type: 'MATERIAL', coefficient: 1.0, unitPrice: 120.00 },
      { code: 'INS-00048', description: 'Dobradiça 3.5"', unit: 'un', type: 'MATERIAL', coefficient: 3.0, unitPrice: 12.50 },
      { code: 'INS-00049', description: 'Parafuso para dobradiça', unit: 'un', type: 'MATERIAL', coefficient: 18.0, unitPrice: 0.35 },
      { code: 'INS-00050', description: 'Espuma expansiva', unit: 'un', type: 'MATERIAL', coefficient: 0.5, unitPrice: 28.00 },
      { code: 'INS-00009', description: 'Carpinteiro', unit: 'h', type: 'LABOR', coefficient: 2.5, unitPrice: 23.80 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 1.0, unitPrice: 18.55 },
    ],
  },
  {
    code: 'SINAPI-91340',
    description: 'Janela de alumínio de correr 2 folhas, 120x120cm, vidro liso',
    unit: 'un',
    category: '07',
    subcategory: 'Esquadrias',
    baseCost: 680.00,
    items: [
      { code: 'INS-00051', description: 'Janela alumínio 120x120cm', unit: 'un', type: 'MATERIAL', coefficient: 1.0, unitPrice: 480.00 },
      { code: 'INS-00052', description: 'Vidro liso 4mm', unit: 'm²', type: 'MATERIAL', coefficient: 1.44, unitPrice: 42.00 },
      { code: 'INS-00050', description: 'Espuma expansiva', unit: 'un', type: 'MATERIAL', coefficient: 1.0, unitPrice: 28.00 },
      { code: 'INS-00005', description: 'Pedreiro', unit: 'h', type: 'LABOR', coefficient: 1.5, unitPrice: 23.10 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 1.0, unitPrice: 18.55 },
    ],
  },
  {
    code: 'SINAPI-91342',
    description: 'Porta de alumínio de abrir, 90x210cm, com vidro temperado',
    unit: 'un',
    category: '07',
    subcategory: 'Esquadrias',
    baseCost: 1350.00,
    items: [
      { code: 'INS-00053', description: 'Porta alumínio 90x210cm', unit: 'un', type: 'MATERIAL', coefficient: 1.0, unitPrice: 950.00 },
      { code: 'INS-00054', description: 'Vidro temperado 8mm', unit: 'm²', type: 'MATERIAL', coefficient: 1.89, unitPrice: 125.00 },
      { code: 'INS-00050', description: 'Espuma expansiva', unit: 'un', type: 'MATERIAL', coefficient: 1.0, unitPrice: 28.00 },
      { code: 'INS-00005', description: 'Pedreiro', unit: 'h', type: 'LABOR', coefficient: 2.0, unitPrice: 23.10 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 1.5, unitPrice: 18.55 },
    ],
  },
  {
    code: 'SINAPI-91344',
    description: 'Janela basculante de alumínio 60x60cm, vidro fantasia',
    unit: 'un',
    category: '07',
    subcategory: 'Esquadrias',
    baseCost: 295.00,
    items: [
      { code: 'INS-00055', description: 'Janela basculante alumínio 60x60cm', unit: 'un', type: 'MATERIAL', coefficient: 1.0, unitPrice: 195.00 },
      { code: 'INS-00056', description: 'Vidro fantasia 4mm', unit: 'm²', type: 'MATERIAL', coefficient: 0.36, unitPrice: 55.00 },
      { code: 'INS-00050', description: 'Espuma expansiva', unit: 'un', type: 'MATERIAL', coefficient: 0.5, unitPrice: 28.00 },
      { code: 'INS-00005', description: 'Pedreiro', unit: 'h', type: 'LABOR', coefficient: 1.0, unitPrice: 23.10 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 0.5, unitPrice: 18.55 },
    ],
  },

  // ══════════════════════════════════════════════════════════════
  // ETAPA 08 - REVESTIMENTOS
  // ══════════════════════════════════════════════════════════════
  {
    code: 'SINAPI-87878',
    description: 'Chapisco em parede interna, argamassa 1:3 (cimento e areia)',
    unit: 'm²',
    category: '08',
    subcategory: 'Revestimentos',
    baseCost: 8.50,
    items: [
      { code: 'INS-00011', description: 'Cimento CP-II', unit: 'kg', type: 'MATERIAL', coefficient: 2.5, unitPrice: 0.62 },
      { code: 'INS-00012', description: 'Areia média', unit: 'm³', type: 'MATERIAL', coefficient: 0.005, unitPrice: 95.00 },
      { code: 'INS-00005', description: 'Pedreiro', unit: 'h', type: 'LABOR', coefficient: 0.15, unitPrice: 23.10 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 0.1, unitPrice: 18.55 },
    ],
  },
  {
    code: 'SINAPI-87879',
    description: 'Emboço/massa única interna, argamassa traço 1:2:8, e=20mm',
    unit: 'm²',
    category: '08',
    subcategory: 'Revestimentos',
    baseCost: 28.50,
    items: [
      { code: 'INS-00011', description: 'Cimento CP-II', unit: 'kg', type: 'MATERIAL', coefficient: 4.0, unitPrice: 0.62 },
      { code: 'INS-00027', description: 'Cal hidratada', unit: 'kg', type: 'MATERIAL', coefficient: 2.5, unitPrice: 0.55 },
      { code: 'INS-00012', description: 'Areia média', unit: 'm³', type: 'MATERIAL', coefficient: 0.02, unitPrice: 95.00 },
      { code: 'INS-00005', description: 'Pedreiro', unit: 'h', type: 'LABOR', coefficient: 0.55, unitPrice: 23.10 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 0.35, unitPrice: 18.55 },
    ],
  },
  {
    code: 'SINAPI-87880',
    description: 'Reboco interno, argamassa traço 1:2:8, e=5mm',
    unit: 'm²',
    category: '08',
    subcategory: 'Revestimentos',
    baseCost: 18.20,
    items: [
      { code: 'INS-00011', description: 'Cimento CP-II', unit: 'kg', type: 'MATERIAL', coefficient: 1.5, unitPrice: 0.62 },
      { code: 'INS-00027', description: 'Cal hidratada', unit: 'kg', type: 'MATERIAL', coefficient: 1.0, unitPrice: 0.55 },
      { code: 'INS-00012', description: 'Areia média', unit: 'm³', type: 'MATERIAL', coefficient: 0.005, unitPrice: 95.00 },
      { code: 'INS-00005', description: 'Pedreiro', unit: 'h', type: 'LABOR', coefficient: 0.4, unitPrice: 23.10 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 0.25, unitPrice: 18.55 },
    ],
  },
  {
    code: 'SINAPI-87882',
    description: 'Revestimento cerâmico para parede, PEI-3, argamassa colante',
    unit: 'm²',
    category: '08',
    subcategory: 'Revestimentos',
    baseCost: 68.50,
    items: [
      { code: 'INS-00057', description: 'Cerâmica para parede 30x60cm', unit: 'm²', type: 'MATERIAL', coefficient: 1.1, unitPrice: 32.00 },
      { code: 'INS-00058', description: 'Argamassa colante AC-I', unit: 'kg', type: 'MATERIAL', coefficient: 5.0, unitPrice: 0.65 },
      { code: 'INS-00059', description: 'Rejunte cimentício', unit: 'kg', type: 'MATERIAL', coefficient: 0.5, unitPrice: 5.80 },
      { code: 'INS-00060', description: 'Azulejista', unit: 'h', type: 'LABOR', coefficient: 0.8, unitPrice: 25.00 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 0.4, unitPrice: 18.55 },
    ],
  },
  {
    code: 'SINAPI-87884',
    description: 'Chapisco externo, argamassa 1:3 (cimento e areia grossa)',
    unit: 'm²',
    category: '08',
    subcategory: 'Revestimentos',
    baseCost: 9.80,
    items: [
      { code: 'INS-00011', description: 'Cimento CP-II', unit: 'kg', type: 'MATERIAL', coefficient: 2.8, unitPrice: 0.62 },
      { code: 'INS-00061', description: 'Areia grossa', unit: 'm³', type: 'MATERIAL', coefficient: 0.006, unitPrice: 98.00 },
      { code: 'INS-00005', description: 'Pedreiro', unit: 'h', type: 'LABOR', coefficient: 0.18, unitPrice: 23.10 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 0.12, unitPrice: 18.55 },
    ],
  },
  {
    code: 'CF-08001',
    description: 'Mestramento de paredes internas com argamassa traço 1:2:8 (taliscas e mestras)',
    unit: 'm²',
    category: '08',
    subcategory: 'Revestimentos',
    baseCost: 3.80,
    items: [
      { code: 'INS-00011', description: 'Cimento CP-II', unit: 'kg', type: 'MATERIAL', coefficient: 0.8, unitPrice: 0.62 },
      { code: 'INS-00027', description: 'Cal hidratada', unit: 'kg', type: 'MATERIAL', coefficient: 0.5, unitPrice: 0.55 },
      { code: 'INS-00012', description: 'Areia média', unit: 'm³', type: 'MATERIAL', coefficient: 0.002, unitPrice: 95.00 },
      { code: 'INS-00005', description: 'Pedreiro', unit: 'h', type: 'LABOR', coefficient: 0.048, unitPrice: 23.10 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 0.024, unitPrice: 18.55 },
    ],
  },
  {
    code: 'CF-08002',
    description: 'Mestramento de paredes externas com argamassa traço 1:2:8 (taliscas e mestras)',
    unit: 'm²',
    category: '08',
    subcategory: 'Revestimentos',
    baseCost: 4.90,
    items: [
      { code: 'INS-00011', description: 'Cimento CP-II', unit: 'kg', type: 'MATERIAL', coefficient: 1.0, unitPrice: 0.62 },
      { code: 'INS-00027', description: 'Cal hidratada', unit: 'kg', type: 'MATERIAL', coefficient: 0.6, unitPrice: 0.55 },
      { code: 'INS-00012', description: 'Areia média', unit: 'm³', type: 'MATERIAL', coefficient: 0.003, unitPrice: 95.00 },
      { code: 'INS-00005', description: 'Pedreiro', unit: 'h', type: 'LABOR', coefficient: 0.06, unitPrice: 23.10 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 0.036, unitPrice: 18.55 },
    ],
  },
  {
    code: 'SINAPI-87881',
    description: 'Reboco externo, argamassa traço 1:2:6, e=25mm, com mestras',
    unit: 'm²',
    category: '08',
    subcategory: 'Revestimentos',
    baseCost: 32.00,
    items: [
      { code: 'INS-00011', description: 'Cimento CP-II', unit: 'kg', type: 'MATERIAL', coefficient: 5.5, unitPrice: 0.62 },
      { code: 'INS-00027', description: 'Cal hidratada', unit: 'kg', type: 'MATERIAL', coefficient: 2.0, unitPrice: 0.55 },
      { code: 'INS-00012', description: 'Areia média', unit: 'm³', type: 'MATERIAL', coefficient: 0.025, unitPrice: 95.00 },
      { code: 'INS-00005', description: 'Pedreiro', unit: 'h', type: 'LABOR', coefficient: 0.65, unitPrice: 23.10 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 0.4, unitPrice: 18.55 },
    ],
  },
  {
    code: 'CF-08003',
    description: 'Revestimento de parede em porcelanato grande formato 1,20x1,20m, com argamassa ACIII',
    unit: 'm²',
    category: '08',
    subcategory: 'Revestimentos',
    baseCost: 195.00,
    items: [
      { code: 'INS-00164', description: 'Porcelanato grande formato 1,20x1,20m', unit: 'm²', type: 'MATERIAL', coefficient: 1.08, unitPrice: 115.00 },
      { code: 'INS-00165', description: 'Argamassa colante AC-III', unit: 'kg', type: 'MATERIAL', coefficient: 6.0, unitPrice: 2.80 },
      { code: 'INS-00166', description: 'Espaçador nivelador (kit)', unit: 'un', type: 'MATERIAL', coefficient: 8.0, unitPrice: 0.85 },
      { code: 'INS-00060', description: 'Azulejista', unit: 'h', type: 'LABOR', coefficient: 1.2, unitPrice: 25.00 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 0.6, unitPrice: 18.55 },
    ],
  },
  {
    code: 'CF-08004',
    description: 'Rejuntamento de revestimento cerâmico/porcelanato em paredes, junta mínima',
    unit: 'm²',
    category: '08',
    subcategory: 'Revestimentos',
    baseCost: 8.90,
    items: [
      { code: 'INS-00059', description: 'Rejunte cimentício', unit: 'kg', type: 'MATERIAL', coefficient: 0.8, unitPrice: 5.80 },
      { code: 'INS-00167', description: 'Esponja para rejunte', unit: 'un', type: 'MATERIAL', coefficient: 0.1, unitPrice: 8.00 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 0.2, unitPrice: 18.55 },
    ],
  },
  {
    code: 'CF-08005',
    description: 'Montagem e desmontagem de andaime tubular para revestimento externo em fachada, h até 10m',
    unit: 'm²',
    category: '08',
    subcategory: 'Revestimentos',
    baseCost: 22.00,
    items: [
      { code: 'INS-00168', description: 'Locação de andaime tubular (mês)', unit: 'm²', type: 'MATERIAL', coefficient: 1.0, unitPrice: 12.00 },
      { code: 'INS-00169', description: 'Tábua para plataforma', unit: 'm', type: 'MATERIAL', coefficient: 0.5, unitPrice: 5.50 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 0.35, unitPrice: 18.55 },
      { code: 'INS-00020', description: 'Armador', unit: 'h', type: 'LABOR', coefficient: 0.2, unitPrice: 23.50 },
    ],
  },

  // ══════════════════════════════════════════════════════════════
  // ETAPA 09 - PISOS
  // ══════════════════════════════════════════════════════════════
  {
    code: 'SINAPI-87261',
    description: 'Contrapiso em argamassa traço 1:4, e=4cm, desempenado',
    unit: 'm²',
    category: '09',
    subcategory: 'Pisos',
    baseCost: 35.00,
    items: [
      { code: 'INS-00011', description: 'Cimento CP-II', unit: 'kg', type: 'MATERIAL', coefficient: 8.0, unitPrice: 0.62 },
      { code: 'INS-00012', description: 'Areia média', unit: 'm³', type: 'MATERIAL', coefficient: 0.04, unitPrice: 95.00 },
      { code: 'INS-00005', description: 'Pedreiro', unit: 'h', type: 'LABOR', coefficient: 0.5, unitPrice: 23.10 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 0.35, unitPrice: 18.55 },
    ],
  },
  {
    code: 'SINAPI-87263',
    description: 'Piso cerâmico 45x45cm PEI-4, argamassa colante, rejunte',
    unit: 'm²',
    category: '09',
    subcategory: 'Pisos',
    baseCost: 72.00,
    items: [
      { code: 'INS-00062', description: 'Piso cerâmico 45x45cm', unit: 'm²', type: 'MATERIAL', coefficient: 1.1, unitPrice: 35.00 },
      { code: 'INS-00058', description: 'Argamassa colante AC-I', unit: 'kg', type: 'MATERIAL', coefficient: 5.5, unitPrice: 0.65 },
      { code: 'INS-00059', description: 'Rejunte cimentício', unit: 'kg', type: 'MATERIAL', coefficient: 0.6, unitPrice: 5.80 },
      { code: 'INS-00060', description: 'Azulejista', unit: 'h', type: 'LABOR', coefficient: 0.65, unitPrice: 25.00 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 0.35, unitPrice: 18.55 },
    ],
  },
  {
    code: 'SINAPI-87265',
    description: 'Porcelanato polido 60x60cm, argamassa colante AC-II',
    unit: 'm²',
    category: '09',
    subcategory: 'Pisos',
    baseCost: 125.00,
    items: [
      { code: 'INS-00063', description: 'Porcelanato polido 60x60cm', unit: 'm²', type: 'MATERIAL', coefficient: 1.1, unitPrice: 72.00 },
      { code: 'INS-00064', description: 'Argamassa colante AC-II', unit: 'kg', type: 'MATERIAL', coefficient: 5.5, unitPrice: 0.95 },
      { code: 'INS-00059', description: 'Rejunte cimentício', unit: 'kg', type: 'MATERIAL', coefficient: 0.5, unitPrice: 5.80 },
      { code: 'INS-00060', description: 'Azulejista', unit: 'h', type: 'LABOR', coefficient: 0.8, unitPrice: 25.00 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 0.4, unitPrice: 18.55 },
    ],
  },
  {
    code: 'SINAPI-87267',
    description: 'Rodapé cerâmico 8x45cm, argamassa colante',
    unit: 'm',
    category: '09',
    subcategory: 'Pisos',
    baseCost: 18.50,
    items: [
      { code: 'INS-00065', description: 'Rodapé cerâmico 8cm', unit: 'm', type: 'MATERIAL', coefficient: 1.05, unitPrice: 8.50 },
      { code: 'INS-00058', description: 'Argamassa colante AC-I', unit: 'kg', type: 'MATERIAL', coefficient: 1.5, unitPrice: 0.65 },
      { code: 'INS-00059', description: 'Rejunte cimentício', unit: 'kg', type: 'MATERIAL', coefficient: 0.1, unitPrice: 5.80 },
      { code: 'INS-00060', description: 'Azulejista', unit: 'h', type: 'LABOR', coefficient: 0.2, unitPrice: 25.00 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 0.1, unitPrice: 18.55 },
    ],
  },
  {
    code: 'CF-09001',
    description: 'Compactação de solo com compactador tipo sapo/placa vibratória, preparação para contrapiso',
    unit: 'm²',
    category: '09',
    subcategory: 'Pisos',
    baseCost: 8.50,
    items: [
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 0.2, unitPrice: 18.55 },
      { code: 'INS-00170', description: 'Compactador de solo tipo placa vibratória', unit: 'h', type: 'EQUIPMENT', coefficient: 0.08, unitPrice: 35.00 },
      { code: 'INS-00171', description: 'Água para compactação', unit: 'm³', type: 'MATERIAL', coefficient: 0.01, unitPrice: 12.00 },
    ],
  },
  {
    code: 'CF-09002',
    description: 'Mestramento e estudo de nível de piso com argamassa (mestras e taliscas para contrapiso)',
    unit: 'm²',
    category: '09',
    subcategory: 'Pisos',
    baseCost: 10.80,
    items: [
      { code: 'INS-00011', description: 'Cimento CP-II', unit: 'kg', type: 'MATERIAL', coefficient: 1.2, unitPrice: 0.62 },
      { code: 'INS-00012', description: 'Areia média', unit: 'm³', type: 'MATERIAL', coefficient: 0.004, unitPrice: 95.00 },
      { code: 'INS-00005', description: 'Pedreiro', unit: 'h', type: 'LABOR', coefficient: 0.22, unitPrice: 23.10 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 0.12, unitPrice: 18.55 },
    ],
  },
  {
    code: 'CF-09003',
    description: 'Paginação de piso (demarcação de juntas, recortes e alinhamento para assentamento)',
    unit: 'm²',
    category: '09',
    subcategory: 'Pisos',
    baseCost: 15.00,
    items: [
      { code: 'INS-00172', description: 'Linha de nylon para paginação', unit: 'un', type: 'MATERIAL', coefficient: 0.05, unitPrice: 8.00 },
      { code: 'INS-00060', description: 'Azulejista', unit: 'h', type: 'LABOR', coefficient: 0.35, unitPrice: 25.00 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 0.2, unitPrice: 18.55 },
    ],
  },
  {
    code: 'CF-09004',
    description: 'Revestimento de piso em porcelanato grande formato 1,20x1,20m, com argamassa ACIII',
    unit: 'm²',
    category: '09',
    subcategory: 'Pisos',
    baseCost: 205.00,
    items: [
      { code: 'INS-00164', description: 'Porcelanato grande formato 1,20x1,20m', unit: 'm²', type: 'MATERIAL', coefficient: 1.08, unitPrice: 115.00 },
      { code: 'INS-00165', description: 'Argamassa colante AC-III', unit: 'kg', type: 'MATERIAL', coefficient: 7.0, unitPrice: 2.80 },
      { code: 'INS-00166', description: 'Espaçador nivelador (kit)', unit: 'un', type: 'MATERIAL', coefficient: 8.0, unitPrice: 0.85 },
      { code: 'INS-00059', description: 'Rejunte cimentício', unit: 'kg', type: 'MATERIAL', coefficient: 0.5, unitPrice: 5.80 },
      { code: 'INS-00060', description: 'Azulejista', unit: 'h', type: 'LABOR', coefficient: 1.0, unitPrice: 25.00 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 0.5, unitPrice: 18.55 },
    ],
  },
  {
    code: 'CF-09005',
    description: 'Rejuntamento de piso cerâmico/porcelanato, junta mínima, rejunte cimentício',
    unit: 'm²',
    category: '09',
    subcategory: 'Pisos',
    baseCost: 8.60,
    items: [
      { code: 'INS-00059', description: 'Rejunte cimentício', unit: 'kg', type: 'MATERIAL', coefficient: 0.7, unitPrice: 5.80 },
      { code: 'INS-00167', description: 'Esponja para rejunte', unit: 'un', type: 'MATERIAL', coefficient: 0.1, unitPrice: 8.00 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 0.2, unitPrice: 18.55 },
    ],
  },
  {
    code: 'CF-09006',
    description: 'Rodapé de porcelanato 8x120cm, assentado com argamassa ACIII, rejuntado',
    unit: 'm',
    category: '09',
    subcategory: 'Pisos',
    baseCost: 32.00,
    items: [
      { code: 'INS-00176', description: 'Rodapé porcelanato 8x120cm', unit: 'm', type: 'MATERIAL', coefficient: 1.08, unitPrice: 18.00 },
      { code: 'INS-00165', description: 'Argamassa colante AC-III', unit: 'kg', type: 'MATERIAL', coefficient: 1.2, unitPrice: 2.80 },
      { code: 'INS-00059', description: 'Rejunte cimentício', unit: 'kg', type: 'MATERIAL', coefficient: 0.08, unitPrice: 5.80 },
      { code: 'INS-00060', description: 'Azulejista', unit: 'h', type: 'LABOR', coefficient: 0.2, unitPrice: 25.00 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 0.1, unitPrice: 18.55 },
    ],
  },
  {
    code: 'CF-09007',
    description: 'Rodapé de poliestireno (tipo Santa Luzia) 7cm, fixado com adesivo',
    unit: 'm',
    category: '09',
    subcategory: 'Pisos',
    baseCost: 20.90,
    items: [
      { code: 'INS-00177', description: 'Rodapé poliestireno Santa Luzia 7cm', unit: 'm', type: 'MATERIAL', coefficient: 1.05, unitPrice: 12.50 },
      { code: 'INS-00178', description: 'Adesivo de fixação para rodapé', unit: 'ml', type: 'MATERIAL', coefficient: 30.0, unitPrice: 0.08 },
      { code: 'INS-00009', description: 'Carpinteiro', unit: 'h', type: 'LABOR', coefficient: 0.12, unitPrice: 23.80 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 0.06, unitPrice: 18.55 },
    ],
  },
  {
    code: 'SINAPI-87269',
    description: 'Soleira de granito cinza polido, l=15cm, e=2cm',
    unit: 'm',
    category: '09',
    subcategory: 'Pisos',
    baseCost: 85.00,
    items: [
      { code: 'INS-00066', description: 'Soleira granito cinza 15cm', unit: 'm', type: 'MATERIAL', coefficient: 1.05, unitPrice: 55.00 },
      { code: 'INS-00064', description: 'Argamassa colante AC-II', unit: 'kg', type: 'MATERIAL', coefficient: 2.0, unitPrice: 0.95 },
      { code: 'INS-00005', description: 'Pedreiro', unit: 'h', type: 'LABOR', coefficient: 0.4, unitPrice: 23.10 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 0.2, unitPrice: 18.55 },
    ],
  },

  // ══════════════════════════════════════════════════════════════
  // ETAPA 10 - PINTURA
  // ══════════════════════════════════════════════════════════════
  {
    code: 'SINAPI-88489',
    description: 'Pintura PVA látex 2 demãos, sobre parede já preparada',
    unit: 'm²',
    category: '10',
    subcategory: 'Pintura',
    baseCost: 12.00,
    items: [
      { code: 'INS-00067', description: 'Tinta PVA látex', unit: 'l', type: 'MATERIAL', coefficient: 0.25, unitPrice: 18.00 },
      { code: 'INS-00070', description: 'Pintor', unit: 'h', type: 'LABOR', coefficient: 0.3, unitPrice: 23.00 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 0.1, unitPrice: 18.55 },
    ],
  },
  {
    code: 'SINAPI-88491',
    description: 'Pintura acrílica 2 demãos, sobre massa corrida',
    unit: 'm²',
    category: '10',
    subcategory: 'Pintura',
    baseCost: 28.00,
    items: [
      { code: 'INS-00071', description: 'Tinta acrílica premium', unit: 'l', type: 'MATERIAL', coefficient: 0.25, unitPrice: 28.00 },
      { code: 'INS-00072', description: 'Massa acrílica', unit: 'l', type: 'MATERIAL', coefficient: 0.5, unitPrice: 10.50 },
      { code: 'INS-00069', description: 'Lixa nº 120', unit: 'un', type: 'MATERIAL', coefficient: 0.2, unitPrice: 2.50 },
      { code: 'INS-00070', description: 'Pintor', unit: 'h', type: 'LABOR', coefficient: 0.45, unitPrice: 23.00 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 0.15, unitPrice: 18.55 },
    ],
  },
  {
    code: 'SINAPI-88493',
    description: 'Pintura texturizada acrílica, rolo de espuma',
    unit: 'm²',
    category: '10',
    subcategory: 'Pintura',
    baseCost: 18.00,
    items: [
      { code: 'INS-00073', description: 'Textura acrílica', unit: 'l', type: 'MATERIAL', coefficient: 0.6, unitPrice: 15.00 },
      { code: 'INS-00070', description: 'Pintor', unit: 'h', type: 'LABOR', coefficient: 0.3, unitPrice: 23.00 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 0.15, unitPrice: 18.55 },
    ],
  },
  {
    code: 'SINAPI-88495',
    description: 'Emassamento de parede com massa corrida PVA, 2 demãos',
    unit: 'm²',
    category: '10',
    subcategory: 'Pintura',
    baseCost: 12.50,
    items: [
      { code: 'INS-00068', description: 'Massa corrida PVA', unit: 'l', type: 'MATERIAL', coefficient: 0.6, unitPrice: 8.50 },
      { code: 'INS-00069', description: 'Lixa nº 120', unit: 'un', type: 'MATERIAL', coefficient: 0.3, unitPrice: 2.50 },
      { code: 'INS-00070', description: 'Pintor', unit: 'h', type: 'LABOR', coefficient: 0.3, unitPrice: 23.00 },
    ],
  },

  {
    code: 'CF-10001',
    description: 'Aplicação de selador acrílico em paredes internas e externas, 1 demão',
    unit: 'm²',
    category: '10',
    subcategory: 'Pintura',
    baseCost: 5.80,
    items: [
      { code: 'INS-00180', description: 'Selador acrílico', unit: 'l', type: 'MATERIAL', coefficient: 0.16, unitPrice: 14.00 },
      { code: 'INS-00070', description: 'Pintor', unit: 'h', type: 'LABOR', coefficient: 0.08, unitPrice: 23.00 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 0.04, unitPrice: 18.55 },
    ],
  },
  {
    code: 'CF-10002',
    description: 'Emassamento de parede com massa acrílica, 2 demãos, incluindo lixamento',
    unit: 'm²',
    category: '10',
    subcategory: 'Pintura',
    baseCost: 18.50,
    items: [
      { code: 'INS-00072', description: 'Massa acrílica', unit: 'l', type: 'MATERIAL', coefficient: 0.6, unitPrice: 10.50 },
      { code: 'INS-00069', description: 'Lixa nº 120', unit: 'un', type: 'MATERIAL', coefficient: 0.4, unitPrice: 2.50 },
      { code: 'INS-00070', description: 'Pintor', unit: 'h', type: 'LABOR', coefficient: 0.35, unitPrice: 23.00 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 0.1, unitPrice: 18.55 },
    ],
  },
  {
    code: 'CF-10003',
    description: 'Aplicação de textura Grafiatto em paredes externas, rolo ou desempenadeira',
    unit: 'm²',
    category: '10',
    subcategory: 'Pintura',
    baseCost: 28.00,
    items: [
      { code: 'INS-00181', description: 'Textura Grafiatto', unit: 'kg', type: 'MATERIAL', coefficient: 2.5, unitPrice: 5.50 },
      { code: 'INS-00180', description: 'Selador acrílico (base)', unit: 'l', type: 'MATERIAL', coefficient: 0.12, unitPrice: 14.00 },
      { code: 'INS-00070', description: 'Pintor', unit: 'h', type: 'LABOR', coefficient: 0.4, unitPrice: 23.00 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 0.15, unitPrice: 18.55 },
    ],
  },

  {
    code: 'CF-10005',
    description: 'Emassamento de forro/teto com massa corrida PVA, 2 demãos, incluindo lixamento',
    unit: 'm²',
    category: '10',
    subcategory: 'Pintura',
    baseCost: 16.50,
    items: [
      { code: 'INS-00068', description: 'Massa corrida PVA', unit: 'l', type: 'MATERIAL', coefficient: 0.6, unitPrice: 8.50 },
      { code: 'INS-00069', description: 'Lixa nº 120', unit: 'un', type: 'MATERIAL', coefficient: 0.4, unitPrice: 2.50 },
      { code: 'INS-00070', description: 'Pintor', unit: 'h', type: 'LABOR', coefficient: 0.4, unitPrice: 23.00 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 0.12, unitPrice: 18.55 },
    ],
  },
  {
    code: 'CF-10004',
    description: 'Pintura com tinta látex PVA em teto, 2 demãos, sobre superfície já preparada',
    unit: 'm²',
    category: '10',
    subcategory: 'Pintura',
    baseCost: 14.50,
    items: [
      { code: 'INS-00067', description: 'Tinta PVA látex', unit: 'l', type: 'MATERIAL', coefficient: 0.28, unitPrice: 18.00 },
      { code: 'INS-00070', description: 'Pintor', unit: 'h', type: 'LABOR', coefficient: 0.35, unitPrice: 23.00 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 0.12, unitPrice: 18.55 },
    ],
  },

  // ══════════════════════════════════════════════════════════════
  // ETAPA 11 - LOUÇAS E METAIS
  // ══════════════════════════════════════════════════════════════
  {
    code: 'SINAPI-86941',
    description: 'Bacia sanitária com caixa acoplada, louça branca',
    unit: 'un',
    category: '11',
    subcategory: 'Louças e Metais',
    baseCost: 550.00,
    items: [
      { code: 'INS-00074', description: 'Bacia sanitária com caixa acoplada', unit: 'un', type: 'MATERIAL', coefficient: 1.0, unitPrice: 380.00 },
      { code: 'INS-00075', description: 'Parafuso fixação bacia', unit: 'un', type: 'MATERIAL', coefficient: 2.0, unitPrice: 8.50 },
      { code: 'INS-00076', description: 'Anel de vedação', unit: 'un', type: 'MATERIAL', coefficient: 1.0, unitPrice: 12.00 },
      { code: 'INS-00077', description: 'Encanador', unit: 'h', type: 'LABOR', coefficient: 2.0, unitPrice: 25.00 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 1.0, unitPrice: 18.55 },
    ],
  },
  {
    code: 'SINAPI-86943',
    description: 'Lavatório de louça branca com coluna, incluindo torneira',
    unit: 'un',
    category: '11',
    subcategory: 'Louças e Metais',
    baseCost: 420.00,
    items: [
      { code: 'INS-00078', description: 'Lavatório com coluna branco', unit: 'un', type: 'MATERIAL', coefficient: 1.0, unitPrice: 185.00 },
      { code: 'INS-00079', description: 'Torneira cromada para lavatório', unit: 'un', type: 'MATERIAL', coefficient: 1.0, unitPrice: 85.00 },
      { code: 'INS-00080', description: 'Sifão PVC para lavatório', unit: 'un', type: 'MATERIAL', coefficient: 1.0, unitPrice: 18.00 },
      { code: 'INS-00081', description: 'Válvula de escoamento', unit: 'un', type: 'MATERIAL', coefficient: 1.0, unitPrice: 22.00 },
      { code: 'INS-00077', description: 'Encanador', unit: 'h', type: 'LABOR', coefficient: 2.0, unitPrice: 25.00 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 1.0, unitPrice: 18.55 },
    ],
  },
  {
    code: 'SINAPI-86945',
    description: 'Tanque de lavar roupa em louça, com torneira',
    unit: 'un',
    category: '11',
    subcategory: 'Louças e Metais',
    baseCost: 380.00,
    items: [
      { code: 'INS-00082', description: 'Tanque louça branco', unit: 'un', type: 'MATERIAL', coefficient: 1.0, unitPrice: 220.00 },
      { code: 'INS-00083', description: 'Torneira de parede', unit: 'un', type: 'MATERIAL', coefficient: 1.0, unitPrice: 45.00 },
      { code: 'INS-00077', description: 'Encanador', unit: 'h', type: 'LABOR', coefficient: 2.0, unitPrice: 25.00 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 1.0, unitPrice: 18.55 },
    ],
  },
  {
    code: 'SINAPI-86947',
    description: 'Registro de pressão cromado 3/4"',
    unit: 'un',
    category: '11',
    subcategory: 'Louças e Metais',
    baseCost: 95.00,
    items: [
      { code: 'INS-00084', description: 'Registro de pressão 3/4"', unit: 'un', type: 'MATERIAL', coefficient: 1.0, unitPrice: 55.00 },
      { code: 'INS-00085', description: 'Fita veda-rosca', unit: 'un', type: 'MATERIAL', coefficient: 0.2, unitPrice: 5.50 },
      { code: 'INS-00077', description: 'Encanador', unit: 'h', type: 'LABOR', coefficient: 0.5, unitPrice: 25.00 },
    ],
  },
  {
    code: 'SINAPI-86949',
    description: 'Chuveiro elétrico 5500W, incluindo instalação',
    unit: 'un',
    category: '11',
    subcategory: 'Louças e Metais',
    baseCost: 165.00,
    items: [
      { code: 'INS-00086', description: 'Chuveiro elétrico 5500W', unit: 'un', type: 'MATERIAL', coefficient: 1.0, unitPrice: 85.00 },
      { code: 'INS-00087', description: 'Braço chuveiro', unit: 'un', type: 'MATERIAL', coefficient: 1.0, unitPrice: 15.00 },
      { code: 'INS-00015', description: 'Eletricista', unit: 'h', type: 'LABOR', coefficient: 1.0, unitPrice: 25.50 },
      { code: 'INS-00077', description: 'Encanador', unit: 'h', type: 'LABOR', coefficient: 0.5, unitPrice: 25.00 },
    ],
  },

  // ══════════════════════════════════════════════════════════════
  // ETAPA 12 - INSTALAÇÕES ELÉTRICAS
  // ══════════════════════════════════════════════════════════════
  {
    code: 'SINAPI-91926',
    description: 'Ponto de tomada 2P+T, incluindo eletroduto, fiação e caixa',
    unit: 'un',
    category: '12',
    subcategory: 'Instalações Elétricas',
    baseCost: 125.00,
    items: [
      { code: 'INS-00088', description: 'Tomada 2P+T 10A', unit: 'un', type: 'MATERIAL', coefficient: 1.0, unitPrice: 12.50 },
      { code: 'INS-00089', description: 'Eletroduto PVC 3/4"', unit: 'm', type: 'MATERIAL', coefficient: 6.0, unitPrice: 3.20 },
      { code: 'INS-00090', description: 'Fio de cobre 2,5mm²', unit: 'm', type: 'MATERIAL', coefficient: 15.0, unitPrice: 2.80 },
      { code: 'INS-00091', description: 'Caixa 4x2" PVC', unit: 'un', type: 'MATERIAL', coefficient: 1.0, unitPrice: 2.50 },
      { code: 'INS-00015', description: 'Eletricista', unit: 'h', type: 'LABOR', coefficient: 1.5, unitPrice: 25.50 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 0.8, unitPrice: 18.55 },
    ],
  },
  {
    code: 'SINAPI-91928',
    description: 'Ponto de interruptor simples, incluindo eletroduto e fiação',
    unit: 'un',
    category: '12',
    subcategory: 'Instalações Elétricas',
    baseCost: 115.00,
    items: [
      { code: 'INS-00092', description: 'Interruptor simples', unit: 'un', type: 'MATERIAL', coefficient: 1.0, unitPrice: 10.50 },
      { code: 'INS-00089', description: 'Eletroduto PVC 3/4"', unit: 'm', type: 'MATERIAL', coefficient: 5.0, unitPrice: 3.20 },
      { code: 'INS-00090', description: 'Fio de cobre 2,5mm²', unit: 'm', type: 'MATERIAL', coefficient: 12.0, unitPrice: 2.80 },
      { code: 'INS-00091', description: 'Caixa 4x2" PVC', unit: 'un', type: 'MATERIAL', coefficient: 1.0, unitPrice: 2.50 },
      { code: 'INS-00015', description: 'Eletricista', unit: 'h', type: 'LABOR', coefficient: 1.3, unitPrice: 25.50 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 0.7, unitPrice: 18.55 },
    ],
  },
  {
    code: 'SINAPI-91930',
    description: 'Disjuntor termomagnético monopolar 20A',
    unit: 'un',
    category: '12',
    subcategory: 'Instalações Elétricas',
    baseCost: 42.00,
    items: [
      { code: 'INS-00093', description: 'Disjuntor monopolar 20A', unit: 'un', type: 'MATERIAL', coefficient: 1.0, unitPrice: 18.50 },
      { code: 'INS-00015', description: 'Eletricista', unit: 'h', type: 'LABOR', coefficient: 0.5, unitPrice: 25.50 },
    ],
  },
  {
    code: 'SINAPI-91932',
    description: 'Quadro de distribuição de embutir, 18 disjuntores, com barramento',
    unit: 'un',
    category: '12',
    subcategory: 'Instalações Elétricas',
    baseCost: 280.00,
    items: [
      { code: 'INS-00094', description: 'Quadro distribuição 18 disj.', unit: 'un', type: 'MATERIAL', coefficient: 1.0, unitPrice: 165.00 },
      { code: 'INS-00095', description: 'Barramento trifásico', unit: 'un', type: 'MATERIAL', coefficient: 1.0, unitPrice: 35.00 },
      { code: 'INS-00015', description: 'Eletricista', unit: 'h', type: 'LABOR', coefficient: 2.5, unitPrice: 25.50 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 1.0, unitPrice: 18.55 },
    ],
  },
  {
    code: 'SINAPI-91934',
    description: 'Luminária de embutir LED retangular 18W',
    unit: 'un',
    category: '12',
    subcategory: 'Instalações Elétricas',
    baseCost: 85.00,
    items: [
      { code: 'INS-00096', description: 'Luminária LED embutir 18W', unit: 'un', type: 'MATERIAL', coefficient: 1.0, unitPrice: 45.00 },
      { code: 'INS-00015', description: 'Eletricista', unit: 'h', type: 'LABOR', coefficient: 0.8, unitPrice: 25.50 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 0.5, unitPrice: 18.55 },
    ],
  },

  // ══════════════════════════════════════════════════════════════
  // ETAPA 13 - INSTALAÇÕES HIDROSSANITÁRIAS
  // ══════════════════════════════════════════════════════════════
  {
    code: 'SINAPI-89353',
    description: 'Tubo PVC soldável 25mm para água fria, incluindo conexões',
    unit: 'm',
    category: '13',
    subcategory: 'Instalações Hidrossanitárias',
    baseCost: 18.50,
    items: [
      { code: 'INS-00097', description: 'Tubo PVC soldável 25mm', unit: 'm', type: 'MATERIAL', coefficient: 1.05, unitPrice: 5.80 },
      { code: 'INS-00098', description: 'Conexões PVC 25mm (joelhos, tês)', unit: 'un', type: 'MATERIAL', coefficient: 0.8, unitPrice: 3.50 },
      { code: 'INS-00099', description: 'Adesivo PVC', unit: 'un', type: 'MATERIAL', coefficient: 0.02, unitPrice: 18.00 },
      { code: 'INS-00077', description: 'Encanador', unit: 'h', type: 'LABOR', coefficient: 0.3, unitPrice: 25.00 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 0.15, unitPrice: 18.55 },
    ],
  },
  {
    code: 'SINAPI-89355',
    description: 'Tubo PVC esgoto série normal 100mm, incluindo conexões',
    unit: 'm',
    category: '13',
    subcategory: 'Instalações Hidrossanitárias',
    baseCost: 32.00,
    items: [
      { code: 'INS-00100', description: 'Tubo PVC esgoto 100mm', unit: 'm', type: 'MATERIAL', coefficient: 1.05, unitPrice: 14.50 },
      { code: 'INS-00101', description: 'Conexões PVC esgoto 100mm', unit: 'un', type: 'MATERIAL', coefficient: 0.5, unitPrice: 12.00 },
      { code: 'INS-00099', description: 'Adesivo PVC', unit: 'un', type: 'MATERIAL', coefficient: 0.03, unitPrice: 18.00 },
      { code: 'INS-00077', description: 'Encanador', unit: 'h', type: 'LABOR', coefficient: 0.4, unitPrice: 25.00 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 0.2, unitPrice: 18.55 },
    ],
  },
  {
    code: 'SINAPI-89357',
    description: 'Caixa d\'água em polietileno 1000L, com acessórios',
    unit: 'un',
    category: '13',
    subcategory: 'Instalações Hidrossanitárias',
    baseCost: 520.00,
    items: [
      { code: 'INS-00102', description: 'Caixa d\'água 1000L', unit: 'un', type: 'MATERIAL', coefficient: 1.0, unitPrice: 320.00 },
      { code: 'INS-00103', description: 'Torneira boia', unit: 'un', type: 'MATERIAL', coefficient: 1.0, unitPrice: 35.00 },
      { code: 'INS-00104', description: 'Adaptadores e conexões', unit: 'cj', type: 'MATERIAL', coefficient: 1.0, unitPrice: 45.00 },
      { code: 'INS-00077', description: 'Encanador', unit: 'h', type: 'LABOR', coefficient: 3.0, unitPrice: 25.00 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 2.0, unitPrice: 18.55 },
    ],
  },
  {
    code: 'SINAPI-89359',
    description: 'Registro de gaveta bruto 3/4"',
    unit: 'un',
    category: '13',
    subcategory: 'Instalações Hidrossanitárias',
    baseCost: 65.00,
    items: [
      { code: 'INS-00105', description: 'Registro gaveta 3/4"', unit: 'un', type: 'MATERIAL', coefficient: 1.0, unitPrice: 32.00 },
      { code: 'INS-00085', description: 'Fita veda-rosca', unit: 'un', type: 'MATERIAL', coefficient: 0.2, unitPrice: 5.50 },
      { code: 'INS-00077', description: 'Encanador', unit: 'h', type: 'LABOR', coefficient: 0.5, unitPrice: 25.00 },
    ],
  },
  {
    code: 'SINAPI-89361',
    description: 'Caixa sifonada PVC 150x150x50mm',
    unit: 'un',
    category: '13',
    subcategory: 'Instalações Hidrossanitárias',
    baseCost: 42.00,
    items: [
      { code: 'INS-00106', description: 'Caixa sifonada 150x150x50mm', unit: 'un', type: 'MATERIAL', coefficient: 1.0, unitPrice: 18.00 },
      { code: 'INS-00077', description: 'Encanador', unit: 'h', type: 'LABOR', coefficient: 0.5, unitPrice: 25.00 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 0.3, unitPrice: 18.55 },
    ],
  },

  // ══════════════════════════════════════════════════════════════
  // ETAPA 14 - INSTALAÇÕES ESPECIAIS
  // ══════════════════════════════════════════════════════════════
  {
    code: 'SINAPI-91950',
    description: 'SPDA - Para-raios tipo Franklin com mastro',
    unit: 'un',
    category: '14',
    subcategory: 'Instalações Especiais',
    baseCost: 2800.00,
    items: [
      { code: 'INS-00107', description: 'Captor tipo Franklin', unit: 'un', type: 'MATERIAL', coefficient: 1.0, unitPrice: 450.00 },
      { code: 'INS-00108', description: 'Mastro galvanizado 3m', unit: 'un', type: 'MATERIAL', coefficient: 1.0, unitPrice: 280.00 },
      { code: 'INS-00109', description: 'Cabo de cobre nu 35mm²', unit: 'm', type: 'MATERIAL', coefficient: 40.0, unitPrice: 28.00 },
      { code: 'INS-00110', description: 'Haste de aterramento', unit: 'un', type: 'MATERIAL', coefficient: 3.0, unitPrice: 55.00 },
      { code: 'INS-00015', description: 'Eletricista', unit: 'h', type: 'LABOR', coefficient: 12.0, unitPrice: 25.50 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 8.0, unitPrice: 18.55 },
    ],
  },
  {
    code: 'SINAPI-91952',
    description: 'Tubulação de gás GLP, cobre 15mm, incluindo conexões',
    unit: 'm',
    category: '14',
    subcategory: 'Instalações Especiais',
    baseCost: 65.00,
    items: [
      { code: 'INS-00111', description: 'Tubo cobre 15mm', unit: 'm', type: 'MATERIAL', coefficient: 1.05, unitPrice: 32.00 },
      { code: 'INS-00112', description: 'Conexões cobre 15mm', unit: 'un', type: 'MATERIAL', coefficient: 0.5, unitPrice: 18.00 },
      { code: 'INS-00113', description: 'Solda prata', unit: 'g', type: 'MATERIAL', coefficient: 5.0, unitPrice: 0.85 },
      { code: 'INS-00077', description: 'Encanador', unit: 'h', type: 'LABOR', coefficient: 0.5, unitPrice: 25.00 },
    ],
  },
  {
    code: 'SINAPI-91954',
    description: 'Ponto de ar-condicionado split, tubulação e dreno',
    unit: 'un',
    category: '14',
    subcategory: 'Instalações Especiais',
    baseCost: 450.00,
    items: [
      { code: 'INS-00114', description: 'Tubo cobre 1/4" + 1/2"', unit: 'm', type: 'MATERIAL', coefficient: 5.0, unitPrice: 45.00 },
      { code: 'INS-00115', description: 'Dreno PVC 25mm', unit: 'm', type: 'MATERIAL', coefficient: 5.0, unitPrice: 4.50 },
      { code: 'INS-00116', description: 'Cabo elétrico 4mm²', unit: 'm', type: 'MATERIAL', coefficient: 8.0, unitPrice: 5.20 },
      { code: 'INS-00015', description: 'Eletricista', unit: 'h', type: 'LABOR', coefficient: 3.0, unitPrice: 25.50 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 2.0, unitPrice: 18.55 },
    ],
  },

  // ══════════════════════════════════════════════════════════════
  // ETAPA 15 - VIDROS E FERRAGENS
  // ══════════════════════════════════════════════════════════════
  {
    code: 'SINAPI-72131',
    description: 'Vidro temperado 8mm, incolor, instalado',
    unit: 'm²',
    category: '15',
    subcategory: 'Vidros e Ferragens',
    baseCost: 185.00,
    items: [
      { code: 'INS-00054', description: 'Vidro temperado 8mm', unit: 'm²', type: 'MATERIAL', coefficient: 1.05, unitPrice: 125.00 },
      { code: 'INS-00117', description: 'Silicone estrutural', unit: 'un', type: 'MATERIAL', coefficient: 0.3, unitPrice: 32.00 },
      { code: 'INS-00118', description: 'Vidraceiro', unit: 'h', type: 'LABOR', coefficient: 0.8, unitPrice: 28.00 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 0.4, unitPrice: 18.55 },
    ],
  },
  {
    code: 'SINAPI-72133',
    description: 'Fechadura de embutir externa, cromada, completa',
    unit: 'un',
    category: '15',
    subcategory: 'Vidros e Ferragens',
    baseCost: 135.00,
    items: [
      { code: 'INS-00119', description: 'Fechadura embutir externa', unit: 'un', type: 'MATERIAL', coefficient: 1.0, unitPrice: 85.00 },
      { code: 'INS-00009', description: 'Carpinteiro', unit: 'h', type: 'LABOR', coefficient: 0.8, unitPrice: 23.80 },
    ],
  },
  {
    code: 'SINAPI-72135',
    description: 'Fechadura de embutir interna, cromada, tipo alavanca',
    unit: 'un',
    category: '15',
    subcategory: 'Vidros e Ferragens',
    baseCost: 95.00,
    items: [
      { code: 'INS-00120', description: 'Fechadura embutir interna', unit: 'un', type: 'MATERIAL', coefficient: 1.0, unitPrice: 55.00 },
      { code: 'INS-00009', description: 'Carpinteiro', unit: 'h', type: 'LABOR', coefficient: 0.6, unitPrice: 23.80 },
    ],
  },
  {
    code: 'SINAPI-72137',
    description: 'Puxador de porta em alumínio 30cm',
    unit: 'un',
    category: '15',
    subcategory: 'Vidros e Ferragens',
    baseCost: 48.00,
    items: [
      { code: 'INS-00121', description: 'Puxador alumínio 30cm', unit: 'un', type: 'MATERIAL', coefficient: 1.0, unitPrice: 28.00 },
      { code: 'INS-00009', description: 'Carpinteiro', unit: 'h', type: 'LABOR', coefficient: 0.3, unitPrice: 23.80 },
    ],
  },

  // ══════════════════════════════════════════════════════════════
  // ETAPA 16 - PAISAGISMO
  // ══════════════════════════════════════════════════════════════
  {
    code: 'SINAPI-98101',
    description: 'Plantio de grama esmeralda em placas',
    unit: 'm²',
    category: '16',
    subcategory: 'Paisagismo',
    baseCost: 18.50,
    items: [
      { code: 'INS-00122', description: 'Grama esmeralda em placas', unit: 'm²', type: 'MATERIAL', coefficient: 1.1, unitPrice: 8.50 },
      { code: 'INS-00123', description: 'Terra vegetal adubada', unit: 'm³', type: 'MATERIAL', coefficient: 0.03, unitPrice: 85.00 },
      { code: 'INS-00124', description: 'Jardineiro', unit: 'h', type: 'LABOR', coefficient: 0.2, unitPrice: 20.00 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 0.15, unitPrice: 18.55 },
    ],
  },
  {
    code: 'SINAPI-98103',
    description: 'Plantio de muda ornamental, porte médio',
    unit: 'un',
    category: '16',
    subcategory: 'Paisagismo',
    baseCost: 45.00,
    items: [
      { code: 'INS-00125', description: 'Muda ornamental porte médio', unit: 'un', type: 'MATERIAL', coefficient: 1.0, unitPrice: 25.00 },
      { code: 'INS-00123', description: 'Terra vegetal adubada', unit: 'm³', type: 'MATERIAL', coefficient: 0.02, unitPrice: 85.00 },
      { code: 'INS-00124', description: 'Jardineiro', unit: 'h', type: 'LABOR', coefficient: 0.4, unitPrice: 20.00 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 0.3, unitPrice: 18.55 },
    ],
  },
  {
    code: 'SINAPI-98105',
    description: 'Espalhamento de terra vegetal, e=10cm',
    unit: 'm²',
    category: '16',
    subcategory: 'Paisagismo',
    baseCost: 12.00,
    items: [
      { code: 'INS-00123', description: 'Terra vegetal adubada', unit: 'm³', type: 'MATERIAL', coefficient: 0.1, unitPrice: 85.00 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 0.15, unitPrice: 18.55 },
    ],
  },

  // ══════════════════════════════════════════════════════════════
  // ETAPA 17 - LIMPEZA FINAL
  // ══════════════════════════════════════════════════════════════
  {
    code: 'SINAPI-99814',
    description: 'Limpeza geral da obra para entrega',
    unit: 'm²',
    category: '17',
    subcategory: 'Limpeza Final',
    baseCost: 8.50,
    items: [
      { code: 'INS-00126', description: 'Produtos de limpeza', unit: 'cj', type: 'MATERIAL', coefficient: 0.05, unitPrice: 35.00 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 0.35, unitPrice: 18.55 },
    ],
  },
  {
    code: 'SINAPI-99816',
    description: 'Remoção de entulho com caçamba estacionária 5m³',
    unit: 'un',
    category: '17',
    subcategory: 'Limpeza Final',
    baseCost: 380.00,
    items: [
      { code: 'INS-00127', description: 'Caçamba estacionária 5m³', unit: 'un', type: 'MATERIAL', coefficient: 1.0, unitPrice: 280.00 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 4.0, unitPrice: 18.55 },
    ],
  },
  {
    code: 'SINAPI-99818',
    description: 'Polimento de piso de concreto/granilite',
    unit: 'm²',
    category: '17',
    subcategory: 'Limpeza Final',
    baseCost: 15.00,
    items: [
      { code: 'INS-00128', description: 'Cera líquida', unit: 'l', type: 'MATERIAL', coefficient: 0.08, unitPrice: 22.00 },
      { code: 'INS-00001', description: 'Servente', unit: 'h', type: 'LABOR', coefficient: 0.25, unitPrice: 18.55 },
      { code: 'INS-00129', description: 'Politriz elétrica', unit: 'h', type: 'EQUIPMENT', coefficient: 0.15, unitPrice: 35.00 },
    ],
  },

  // ══════════════════════════════════════════════════════════════
  // ETAPA 18 - ADMINISTRAÇÃO DA OBRA
  // ══════════════════════════════════════════════════════════════
  {
    code: 'SINAPI-90778',
    description: 'Engenheiro civil pleno - custo mensal',
    unit: 'mês',
    category: '18',
    subcategory: 'Administração da Obra',
    baseCost: 15500.00,
    items: [
      { code: 'INS-00130', description: 'Engenheiro civil pleno', unit: 'mês', type: 'LABOR', coefficient: 1.0, unitPrice: 15500.00 },
    ],
  },
  {
    code: 'SINAPI-90780',
    description: 'Mestre de obras - custo mensal',
    unit: 'mês',
    category: '18',
    subcategory: 'Administração da Obra',
    baseCost: 7800.00,
    items: [
      { code: 'INS-00131', description: 'Mestre de obras', unit: 'mês', type: 'LABOR', coefficient: 1.0, unitPrice: 7800.00 },
    ],
  },
  {
    code: 'SINAPI-90782',
    description: 'Almoxarife - custo mensal',
    unit: 'mês',
    category: '18',
    subcategory: 'Administração da Obra',
    baseCost: 3500.00,
    items: [
      { code: 'INS-00132', description: 'Almoxarife', unit: 'mês', type: 'LABOR', coefficient: 1.0, unitPrice: 3500.00 },
    ],
  },
  {
    code: 'SINAPI-90784',
    description: 'Vigia noturno - custo mensal',
    unit: 'mês',
    category: '18',
    subcategory: 'Administração da Obra',
    baseCost: 3200.00,
    items: [
      { code: 'INS-00133', description: 'Vigia noturno', unit: 'mês', type: 'LABOR', coefficient: 1.0, unitPrice: 3200.00 },
    ],
  },
  {
    code: 'SINAPI-90786',
    description: 'EPI - Kit completo por trabalhador',
    unit: 'un',
    category: '18',
    subcategory: 'Administração da Obra',
    baseCost: 185.00,
    items: [
      { code: 'INS-00134', description: 'Capacete de segurança', unit: 'un', type: 'MATERIAL', coefficient: 1.0, unitPrice: 25.00 },
      { code: 'INS-00135', description: 'Botina de segurança', unit: 'par', type: 'MATERIAL', coefficient: 1.0, unitPrice: 65.00 },
      { code: 'INS-00136', description: 'Luva de proteção', unit: 'par', type: 'MATERIAL', coefficient: 2.0, unitPrice: 12.00 },
      { code: 'INS-00137', description: 'Óculos de proteção', unit: 'un', type: 'MATERIAL', coefficient: 1.0, unitPrice: 15.00 },
      { code: 'INS-00138', description: 'Protetor auricular', unit: 'un', type: 'MATERIAL', coefficient: 2.0, unitPrice: 8.00 },
      { code: 'INS-00139', description: 'Cinto de segurança', unit: 'un', type: 'MATERIAL', coefficient: 0.5, unitPrice: 85.00 },
    ],
  },
];

// ====================================================================
// HELPER: Calcular preço por estado
// ====================================================================
export function getStateCost(baseCost: number, state: string): number {
  const factor = STATE_PRICE_FACTORS[state] || 1.0;
  return Math.round(baseCost * factor * 100) / 100;
}

// Total de composições
export const TOTAL_COMPOSITIONS = SINAPI_COMPOSITIONS.length;
